type ManagedImage = {
  src: string;
  alt: string;
};

function pexelsPhoto(id: number, width = 1600, height = 1200) {
  return `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${width}&h=${height}&dpr=1`;
}

function buildRegistry(entries: readonly (readonly [string, string, string])[]) {
  return Object.fromEntries(
    entries.map(([key, src, alt]) => [key, { src, alt } satisfies ManagedImage]),
  ) as Record<string, ManagedImage>;
}

const photoLibrary = {
  consultationLead: pexelsPhoto(6129655, 1600, 2000),
  consultationSeated: pexelsPhoto(6129237, 1600, 2000),
  consultationClipboard: pexelsPhoto(6285381, 1600, 2000),
  consultationBlueScrubs: pexelsPhoto(8949872, 1600, 2000),
  patientExam: pexelsPhoto(7659565, 1600, 2000),
  followUpClipboard: pexelsPhoto(9489083, 1600, 2000),
  seniorPatientWalk: pexelsPhoto(7108401, 1600, 2000),
  seniorPatientGuide: pexelsPhoto(7108401, 1600, 2000),
  familyConsultation: pexelsPhoto(7108332, 1600, 2000),
  pediatricConsultation: pexelsPhoto(7108157, 1600, 2000),
  studentHallwayGroup: pexelsPhoto(3985162, 1600, 2000),
  studentHallwayTrio: pexelsPhoto(3985153, 1600, 2000),
  coordinatorReception: pexelsPhoto(6627864, 1600, 2000),
  coordinatorTablet: pexelsPhoto(7659876, 1600, 2000),
  coordinatorDeskConsultation: pexelsPhoto(5452275, 1600, 2000),
  doctorTablet: pexelsPhoto(7433821, 1600, 2000),
  reportReview: pexelsPhoto(4031417, 1600, 1200),
  referralClipboard: pexelsPhoto(6129879, 1600, 1200),
  teamworkTablet: pexelsPhoto(8442101, 1600, 1200),
  executiveMeeting: pexelsPhoto(8538812, 1600, 1200),
  boardroomLaptops: pexelsPhoto(4342498, 1600, 1200),
  boardroomConversation: pexelsPhoto(4343206, 1600, 1200),
  healthcareDelegation: pexelsPhoto(6931199, 1600, 1200),
  hospitalCorridorBright: pexelsPhoto(37036967, 1600, 1200),
  hospitalCorridorSymmetry: pexelsPhoto(11288795, 1600, 1200),
  hospitalCorridorRadiology: pexelsPhoto(11288653, 1600, 1200),
  hospitalWorkerCorridor: pexelsPhoto(36665085, 1600, 1200),
  hospitalExteriorGlass: pexelsPhoto(9741531, 1600, 1200),
  hospitalExteriorModern: pexelsPhoto(10631130, 1600, 1200),
  hospitalExteriorWhite: pexelsPhoto(15005043, 1600, 1200),
  travelSuitcase: pexelsPhoto(20325709, 1200, 1600),
  wheelchairTravel: pexelsPhoto(32176403, 1200, 1600),
  wheelchairHospital: pexelsPhoto(6129108, 1200, 1600),
  wheelchairNurse: pexelsPhoto(6129870, 1200, 1600),
  dentistryProcedure: pexelsPhoto(5622030, 1600, 1200),
  dentistryConsultation: pexelsPhoto(6812535, 1600, 1200),
  emergencyAmbulanceTeam: pexelsPhoto(6520213, 1600, 1200),
  emergencyAmbulance: pexelsPhoto(6754170, 1600, 1200),
  surgeryTeam: pexelsPhoto(32828961, 1600, 1200),
  surgeryRoom: pexelsPhoto(30348333, 1600, 1200),
  patientOnStretcher: pexelsPhoto(36740372, 1600, 1200),
  diagnosticMRI: pexelsPhoto(15277954, 1600, 1200),
  rehabilitationSession: pexelsPhoto(20860580, 1600, 1200),
  pediatricCare: pexelsPhoto(8460049, 1600, 1200),
  babyCheckup: pexelsPhoto(5998446, 1600, 1200),
  gynecologyConsultation: pexelsPhoto(7089329, 1600, 1200),
  labDiagnostics: pexelsPhoto(33916274, 1600, 1200),
  cardiologyConsultation: pexelsPhoto(3735705, 1600, 1200),
  worldMap: pexelsPhoto(9494917, 1600, 1200),
  worldMapHands: pexelsPhoto(8828453, 1600, 1200),
  tashkentSkyline: pexelsPhoto(35070896, 1600, 1200),
  portraitDoctorMale: pexelsPhoto(15752232, 1200, 1200),
  portraitDoctorFemale: pexelsPhoto(12660379, 1200, 1200),
  portraitYoungClinician: pexelsPhoto(32115962, 1200, 1200),
  portraitCoordinator: pexelsPhoto(3747441, 1200, 1200),
  portraitMedicalStudent: pexelsPhoto(19129643, 1200, 1200),
} as const;

const premiumImageEntries = [
  ["about-cta/international-healthcare-conversation", photoLibrary.boardroomConversation, "Healthcare leaders planning an international healthcare collaboration conversation."],
  ["about-hero/hospital-network-visual", photoLibrary.hospitalExteriorGlass, "Modern hospital exterior representing MedPobeda Group's international healthcare network."],
  ["about-hero/leadership-meeting", photoLibrary.executiveMeeting, "Healthcare professionals discussing hospital collaboration."],
  ["about-hero/patient-coordination-desk", photoLibrary.coordinatorTablet, "Healthcare coordination desk supporting patients and institutional partners."],
  ["about-inner/clinical-relevance", photoLibrary.reportReview, "Doctors reviewing clinical information for institutional healthcare planning."],
  ["about-inner/healthcare-bridge", photoLibrary.worldMapHands, "Global healthcare bridge visual connecting healthcare collaboration across regions."],
  ["about-inner/hospital-collaboration", photoLibrary.executiveMeeting, "Hospital leaders in collaboration discussion."],
  ["about-inner/institutional-cooperation", photoLibrary.boardroomLaptops, "Institutional healthcare partnership planning session."],
  ["about-inner/patient-facilitation", photoLibrary.followUpClipboard, "Patient facilitation support inside a clinical consultation setting."],
  ["about-inner/trust-led-communication", photoLibrary.coordinatorReception, "Healthcare coordinator handling trusted communication and patient guidance."],
  ["about-story/clinical-networking", photoLibrary.healthcareDelegation, "Healthcare professionals networking during an institutional collaboration event."],
  ["about-story/doctor-strategy-meeting", photoLibrary.reportReview, "Doctors discussing healthcare strategy and institutional collaboration."],
  ["about-story/executive-hospital-conversation", photoLibrary.boardroomConversation, "Hospital administrators in a professional discussion about healthcare collaboration."],
  ["about-story/patient-family-support", photoLibrary.familyConsultation, "Patient family receiving support during an international healthcare journey."],
  ["about-trust/healthcare-operations-overview", photoLibrary.coordinatorTablet, "Healthcare coordination operations overview with digital case management support."],
  ["about/doctor-roundtable", photoLibrary.boardroomConversation, "Doctors in an international healthcare strategy meeting."],
  ["about/hospital-corridor", photoLibrary.hospitalCorridorBright, "Bright premium hospital corridor representing international healthcare quality."],
  ["about/hospital-executive-meeting", photoLibrary.executiveMeeting, "Healthcare professionals discussing hospital collaboration."],
  ["about/patient-family-guidance", photoLibrary.familyConsultation, "Healthcare coordinator guiding a patient family through treatment planning."],
  ["contact-cta/healthcare-guidance-conversation", photoLibrary.followUpClipboard, "Healthcare guidance conversation for patients, hospitals, and institutions."],
  ["contact-hero/consultation-meeting", photoLibrary.coordinatorDeskConsultation, "Professional healthcare consultation meeting for patient and partnership enquiries."],
  ["contact-hero/international-support", photoLibrary.followUpClipboard, "International healthcare support conversation with a medical coordinator."],
  ["contact-hero/premium-contact-desk", photoLibrary.coordinatorReception, "MedPobeda Group patient and hospital coordination support."],
  ["contact-inner/doctor-collaboration-contact", photoLibrary.reportReview, "Doctors collaborating while reviewing healthcare cases and coordination priorities."],
  ["contact-inner/hospital-partnership-discussion", photoLibrary.boardroomConversation, "Hospital partnership discussion with international healthcare stakeholders."],
  ["contact-inner/patient-support-request", photoLibrary.consultationLead, "Patient support request handled with professional healthcare guidance."],
  ["contact-inner/student-mobility-contact", photoLibrary.studentHallwayTrio, "Student mobility coordination discussion in a clinical setting."],
  ["contact-story/care-coordinator-workspace", photoLibrary.coordinatorTablet, "Healthcare coordinator managing patient and hospital requests from a premium workspace."],
  ["contact-story/hospital-leadership-contact", photoLibrary.executiveMeeting, "Hospital leadership contact meeting for international healthcare collaboration."],
  ["contact-story/institutional-briefing-call", photoLibrary.doctorTablet, "Institutional healthcare briefing supported by digital coordination tools."],
  ["contact-story/patient-inquiry-support", photoLibrary.consultationSeated, "Patient inquiry support during an in-person healthcare consultation."],
  ["contact-trust/tashkent-coordination-base", photoLibrary.tashkentSkyline, "Tashkent-based coordination supporting cross-border healthcare facilitation."],
  ["home-hero/airport-patient-assistance", photoLibrary.wheelchairTravel, "Healthcare coordinator assisting international patient travel support."],
  ["home-hero/doctor-patient-consultation", photoLibrary.consultationLead, "International doctor consulting patient for medical tourism support."],
  ["home-hero/premium-hospital-campus", photoLibrary.hospitalExteriorGlass, "Modern hospital building representing premium international care access."],
  ["international-patients-cta/patient-family-support", photoLibrary.familyConsultation, "Patient family supported by a healthcare coordination team."],
  ["international-patients-hero/caring-doctor-patient", photoLibrary.consultationBlueScrubs, "Doctor providing personalized support for an international patient."],
  ["international-patients-hero/family-reassurance", photoLibrary.familyConsultation, "Family receiving reassurance and treatment guidance from healthcare staff."],
  ["international-patients-hero/patient-coordinator", photoLibrary.coordinatorTablet, "International patient coordinator managing care and travel support."],
  ["international-patients-inner/doctor-selection", photoLibrary.doctorTablet, "Doctor selection support for international patient coordination."],
  ["international-patients-inner/follow-up-coordination", photoLibrary.followUpClipboard, "Follow-up coordination after treatment for international patients."],
  ["international-patients-inner/hospital-appointment-support", photoLibrary.coordinatorReception, "Hospital appointment support for international patients."],
  ["international-patients-inner/language-assistance", photoLibrary.coordinatorDeskConsultation, "Language assistance during healthcare coordination and patient consultation."],
  ["international-patients-inner/travel-stay-support", photoLibrary.wheelchairTravel, "Travel and stay support for international healthcare journeys."],
  ["international-patients-inner/treatment-guidance", photoLibrary.consultationLead, "Treatment guidance for international patients in a premium hospital setting."],
  ["international-patients-story/airport-arrival-support", photoLibrary.wheelchairTravel, "Airport arrival support for international patients."],
  ["international-patients-story/family-guidance-desk", photoLibrary.familyConsultation, "Family guidance desk supporting international patient care decisions."],
  ["international-patients-story/hospital-corridor-assistance", photoLibrary.hospitalWorkerCorridor, "Hospital corridor assistance for international patients and companions."],
  ["international-patients-story/patient-consultation-room", photoLibrary.consultationSeated, "Patient consultation room supporting international care planning."],
  ["international-patients-trust/patient-support-meeting", photoLibrary.coordinatorTablet, "Trusted healthcare coordination and international patient support."],
  ["medical-tourism-cta/patient-consultation-meeting", photoLibrary.consultationLead, "Medical tourism consultation for international patient support."],
  ["medical-tourism-hero/airport-patient-support", photoLibrary.wheelchairTravel, "Medical travel coordination for international patients."],
  ["medical-tourism-hero/doctor-patient-consultation", photoLibrary.consultationSeated, "International doctor consulting patient about treatment options abroad."],
  ["medical-tourism-hero/hospital-campus", photoLibrary.hospitalExteriorGlass, "Premium hospital campus prepared for international patient access."],
  ["medical-tourism-inner/arrival-stay-coordination", photoLibrary.wheelchairHospital, "Arrival and stay coordination for international patient support."],
  ["medical-tourism-inner/doctor-hospital-matching", photoLibrary.doctorTablet, "Doctor and hospital matching based on patient treatment needs."],
  ["medical-tourism-inner/family-follow-through", photoLibrary.familyConsultation, "Family support and follow-through during medical tourism planning."],
  ["medical-tourism-inner/report-review", photoLibrary.reportReview, "Medical report review for treatment planning and specialist coordination."],
  ["medical-tourism-inner/treatment-planning", photoLibrary.consultationClipboard, "Treatment plan and cost estimate discussion for international patients."],
  ["medical-tourism-inner/visa-travel-guidance", photoLibrary.travelSuitcase, "Visa and travel guidance for an international medical journey."],
  ["medical-tourism-story/coordinator-patient-family", photoLibrary.consultationBlueScrubs, "Medical coordinator guiding a patient family through the care journey."],
  ["medical-tourism-story/diagnostics-review", photoLibrary.reportReview, "Diagnostic review and care coordination meeting for medical tourism cases."],
  ["medical-tourism-story/premium-hospital-lobby", photoLibrary.hospitalWorkerCorridor, "Premium hospital corridor and lobby environment for patient arrivals."],
  ["medical-tourism-story/recovery-support", photoLibrary.seniorPatientWalk, "Recovery support and guidance after treatment."],
  ["medical-tourism-trust/care-coordination-meeting", photoLibrary.coordinatorTablet, "Care coordination meeting focused on cross-border treatment support."],
  ["partnerships-cta/hospital-growth-conversation", photoLibrary.executiveMeeting, "Hospital growth conversation for international healthcare collaboration."],
  ["partnerships-hero/doctor-collaboration-roundtable", photoLibrary.reportReview, "Doctors discussing international clinical collaboration and partnership opportunities."],
  ["partnerships-hero/executive-partnership-meeting", photoLibrary.executiveMeeting, "Hospital partnership and healthcare collaboration meeting."],
  ["partnerships-hero/premium-hospital-building", photoLibrary.hospitalExteriorWhite, "Premium hospital building ready for international partnership development."],
  ["partnerships-inner/clinical-training-programs", photoLibrary.studentHallwayGroup, "Clinical training support inside a modern hospital."],
  ["partnerships-inner/doctor-faculty-exchange", photoLibrary.studentHallwayTrio, "Doctor and faculty exchange within a clinical environment."],
  ["partnerships-inner/hospital-branding-abroad", photoLibrary.hospitalExteriorGlass, "Hospital branding and market expansion for international patient access."],
  ["partnerships-inner/international-referrals", photoLibrary.referralClipboard, "International patient referrals reviewed by a healthcare team."],
  ["partnerships-inner/medical-tourism-desk", photoLibrary.coordinatorReception, "Medical tourism desk support inside a partner hospital."],
  ["partnerships-inner/research-conferences", photoLibrary.healthcareDelegation, "Research and conference participation within an international healthcare network."],
  ["partnerships-story/conference-handshake", photoLibrary.executiveMeeting, "Healthcare partnership development meeting."],
  ["partnerships-story/healthcare-delegation", photoLibrary.healthcareDelegation, "International healthcare delegation visit and institutional dialogue."],
  ["partnerships-story/hospital-boardroom", photoLibrary.boardroomLaptops, "Hospital boardroom discussion about cross-border healthcare growth."],
  ["partnerships-story/international-desk-team", photoLibrary.coordinatorReception, "International desk team supporting hospital collaboration."],
  ["partnerships-trust/hospital-leadership-briefing", photoLibrary.boardroomConversation, "Hospital leadership briefing for international partnership strategy."],
  ["partnerships/clinical-training-programs", photoLibrary.studentHallwayGroup, "Clinical training programs for hospital and institutional collaboration."],
  ["partnerships/doctor-faculty-exchange", photoLibrary.studentHallwayTrio, "Doctor and faculty exchange supporting clinical training partnerships."],
  ["partnerships/hospital-branding-abroad", photoLibrary.hospitalExteriorModern, "Hospital branding abroad and international reputation building."],
  ["partnerships/hospital-partner-growth", photoLibrary.hospitalExteriorGlass, "Hospital partner growth through international healthcare collaboration."],
  ["partnerships/international-patient-referrals", photoLibrary.referralClipboard, "International patient referral coordination and hospital collaboration."],
  ["partnerships/medical-tourism-desk-support", photoLibrary.coordinatorReception, "Medical tourism desk support for partner hospitals."],
  ["partnerships/research-and-conferences", photoLibrary.healthcareDelegation, "Research and conference collaboration in healthcare partnerships."],
  ["patients/caring-consultation", photoLibrary.consultationBlueScrubs, "Caring doctor consultation for international patient support."],
  ["patients/doctor-selection", photoLibrary.doctorTablet, "Doctor selection for international healthcare coordination."],
  ["patients/family-health-support", photoLibrary.familyConsultation, "Family healthcare support during an international patient journey."],
  ["patients/follow-up-coordination", photoLibrary.followUpClipboard, "Follow-up coordination between patient and healthcare team."],
  ["patients/hospital-appointment", photoLibrary.coordinatorReception, "Hospital appointment and front desk coordination for international patients."],
  ["patients/language-assistance", photoLibrary.coordinatorDeskConsultation, "Language assistance during patient consultation and healthcare coordination."],
  ["patients/medical-coordinator-desk", photoLibrary.coordinatorTablet, "Medical coordinator providing international patient support."],
  ["patients/travel-and-stay-support", photoLibrary.wheelchairTravel, "Travel and stay support for international healthcare facilitation."],
  ["patients/treatment-guidance", photoLibrary.consultationLead, "Treatment guidance for international patients."],
  ["regions/global-healthcare-bridge", photoLibrary.worldMapHands, "India Uzbekistan healthcare collaboration network."],
  ["services/healthcare-partnership-development", photoLibrary.boardroomLaptops, "Healthcare partnership development meeting."],
  ["services/hospital-collaboration", photoLibrary.executiveMeeting, "Hospital partnership and healthcare collaboration meeting."],
  ["services/international-patient-assistance", photoLibrary.consultationBlueScrubs, "International patient assistance and hospital coordination."],
  ["services/medical-tourism-facilitation", photoLibrary.consultationClipboard, "Medical tourism consultation for international patient."],
  ["services/medical-travel-coordination", photoLibrary.wheelchairTravel, "Medical travel coordination for international patients."],
  ["services/student-mobility-clinical-exposure", photoLibrary.studentHallwayGroup, "Medical students receiving clinical training support."],
  ["specialties/cardiology", photoLibrary.cardiologyConsultation, "Cardiology consultation in a modern clinical setting."],
  ["specialties/dentistry", photoLibrary.dentistryProcedure, "Dentistry treatment and consultation for international patients."],
  ["specialties/diagnostics", photoLibrary.diagnosticMRI, "Diagnostics support including advanced imaging and laboratory review."],
  ["specialties/emergency-care", photoLibrary.emergencyAmbulanceTeam, "Emergency care team responding to a patient support situation."],
  ["specialties/fertility-ivf", photoLibrary.gynecologyConsultation, "Fertility and IVF consultation with compassionate specialist guidance."],
  ["specialties/general-surgery", photoLibrary.surgeryTeam, "General surgery coordination in a premium hospital environment."],
  ["specialties/gynecology", photoLibrary.gynecologyConsultation, "Gynecology consultation with trusted specialist care."],
  ["specialties/neurosurgery", photoLibrary.surgeryRoom, "Neurosurgery planning and advanced operating room support."],
  ["specialties/oncology", photoLibrary.patientExam, "Oncology consultation and patient care planning."],
  ["specialties/orthopedics", photoLibrary.rehabilitationSession, "Orthopedic recovery and mobility-focused treatment support."],
  ["specialties/pediatrics", photoLibrary.pediatricCare, "Pediatric care and family-centered hospital support."],
  ["specialties/rehabilitation", photoLibrary.rehabilitationSession, "Rehabilitation support for recovery and functional improvement."],
  ["student-mobility-cta/clinical-observership-discussion", photoLibrary.studentHallwayTrio, "Clinical observership discussion for international student mobility."],
  ["student-mobility-hero/healthcare-campus", photoLibrary.hospitalExteriorModern, "Healthcare campus supporting international student mobility."],
  ["student-mobility-hero/hospital-student-rounds", photoLibrary.studentHallwayGroup, "Medical students participating in hospital clinical exposure."],
  ["student-mobility-hero/institutional-advising", photoLibrary.boardroomLaptops, "Institutional advising session for student mobility and clinical training support."],
  ["student-mobility-inner/clinical-exposure", photoLibrary.studentHallwayGroup, "Clinical exposure for students inside a hospital setting."],
  ["student-mobility-inner/documentation-readiness", photoLibrary.referralClipboard, "Documentation readiness review for student mobility coordination."],
  ["student-mobility-inner/healthcare-mobility-design", photoLibrary.boardroomLaptops, "Healthcare mobility planning between institutions."],
  ["student-mobility-inner/institutional-collaboration", photoLibrary.healthcareDelegation, "Institutional collaboration for student and faculty mobility."],
  ["student-mobility-inner/international-coordination", photoLibrary.coordinatorTablet, "International coordination for student mobility and hospital exposure."],
  ["student-mobility-inner/observership-internship", photoLibrary.studentHallwayTrio, "Observership and internship support for medical students."],
  ["student-mobility-story/documentation-review", photoLibrary.doctorTablet, "Documentation review for student mobility and observership planning."],
  ["student-mobility-story/faculty-collaboration", photoLibrary.boardroomConversation, "Faculty collaboration meeting supporting clinical training partnerships."],
  ["student-mobility-story/international-welcome", photoLibrary.travelSuitcase, "International welcome support for arriving students."],
  ["student-mobility-story/student-hospital-visit", photoLibrary.studentHallwayGroup, "Medical students on a structured hospital visit."],
  ["student-mobility-trust/institutional-healthcare-briefing", photoLibrary.healthcareDelegation, "Institutional healthcare briefing for student mobility collaboration."],
  ["testimonials/healthcare-coordinator", photoLibrary.portraitDoctorFemale, "Healthcare coordinator testimonial."],
  ["testimonials/hospital-partner", photoLibrary.portraitDoctorMale, "Healthcare partner testimonial."],
  ["testimonials/international-patient", photoLibrary.portraitCoordinator, "International patient testimonial."],
  ["testimonials/medical-student", photoLibrary.portraitMedicalStudent, "Medical student testimonial."],
  ["trust/healthcare-bridge-leadership", photoLibrary.executiveMeeting, "Trusted healthcare coordination and international patient support."],
  ["gallery/hospital-lobby", photoLibrary.hospitalCorridorBright, "Modern hospital lobby and patient reception environment."],
  ["gallery/doctor-rounds", photoLibrary.doctorTablet, "Doctor consultation and specialist rounds inside a hospital."],
  ["gallery/patient-support-desk", photoLibrary.coordinatorReception, "Patient support and hospital reception assistance."],
  ["gallery/medical-airport-arrival", photoLibrary.wheelchairTravel, "Medical travel assistance during airport arrival."],
  ["gallery/executive-partnership-meeting", photoLibrary.executiveMeeting, "Hospital partnership discussion with healthcare stakeholders."],
  ["gallery/student-hospital-visit", photoLibrary.studentHallwayGroup, "Student mobility and clinical hospital exposure."],
  ["gallery/operating-theatre-prep", photoLibrary.surgeryTeam, "Surgical team preparing for advanced treatment support."],
  ["gallery/family-consultation", photoLibrary.familyConsultation, "Family meeting with healthcare specialists for treatment planning."],
  ["gallery/laboratory-diagnostics", photoLibrary.labDiagnostics, "Laboratory diagnostics and clinical testing support."],
  ["gallery/rehabilitation-session", photoLibrary.rehabilitationSession, "Rehabilitation support for patient recovery."],
  ["gallery/hospital-corridor-premium", photoLibrary.hospitalCorridorSymmetry, "Premium hospital corridor with clean international infrastructure."],
  ["gallery/uzbekistan-healthcare-bridge", photoLibrary.tashkentSkyline, "Uzbekistan healthcare bridge and regional coordination network."],
  ["gallery/india-specialist-access", photoLibrary.hospitalExteriorWhite, "India specialist access through premium hospital collaboration."],
  ["gallery/airport-wheelchair-assist", photoLibrary.wheelchairHospital, "Airport and mobility assistance for an international patient journey."],
  ["gallery/clinical-observership", photoLibrary.studentHallwayTrio, "Clinical observership and student mobility support."],
  ["gallery/conference-networking", photoLibrary.healthcareDelegation, "Healthcare conference networking and international delegation support."],
] as const;

const legacyImageEntries = [
  ["/images/home/hero-doctors.jpg", photoLibrary.consultationLead, "International doctor consulting patient for medical tourism support."],
  ["/images/home/hospital-network.jpg", photoLibrary.hospitalExteriorGlass, "Modern hospital exterior representing MedPobeda's international healthcare network."],
  ["/images/home/patient-coordinator.jpg", photoLibrary.coordinatorTablet, "Healthcare coordinator assisting an international patient with treatment planning."],
  ["/images/home/medical-tourism-assistance.jpg", photoLibrary.consultationClipboard, "Medical tourism assistance team helping a patient family prepare for treatment travel."],
  ["/images/home/airport-assistance.jpg", photoLibrary.wheelchairTravel, "International patient assistance representative supporting airport arrival logistics."],
  ["/images/home/medical-reports-review.jpg", photoLibrary.reportReview, "Doctors reviewing medical reports and imaging for an international case assessment."],
  ["/images/home/surgery-treatment-support.jpg", photoLibrary.surgeryTeam, "Hospital team preparing for surgery and treatment coordination support."],
  ["/images/home/accommodation-support.jpg", photoLibrary.familyConsultation, "Patient family discussing accommodation and recovery support near a treatment facility."],
  ["/images/home/hospital-partnership-meeting.jpg", photoLibrary.executiveMeeting, "Hospital administrators in a professional partnership meeting with international healthcare representatives."],
  ["/images/home/patient-success-story.jpg", photoLibrary.seniorPatientWalk, "Recovered patient receiving guided support after treatment."],
  ["/images/home/healthcare-conference.jpg", photoLibrary.healthcareDelegation, "International healthcare conference scene with medical professionals networking."],
  ["/images/home/doctor-team.jpg", photoLibrary.reportReview, "Multidisciplinary doctor team in a premium hospital environment."],
  ["/images/home/global-patient-assistance.jpg", photoLibrary.consultationBlueScrubs, "International patient support team guiding a family through hospital coordination."],
  ["/images/home/cta-consultation.jpg", photoLibrary.consultationLead, "Premium consultation meeting between MedPobeda coordinators and an international healthcare client."],
  ["/images/about/leadership-consultation.jpg", photoLibrary.executiveMeeting, "Healthcare leadership consultation meeting illustrating MedPobeda's professional operating model."],
  ["/images/about/operations-desk.jpg", photoLibrary.coordinatorTablet, "Premium healthcare coordination desk handling international patient and hospital communications."],
  ["/images/about/international-network.jpg", photoLibrary.worldMapHands, "Global medical network visual representing MedPobeda's hospital and specialist access."],
  ["/images/about/team-meeting.jpg", photoLibrary.healthcareDelegation, "MedPobeda leadership and coordinators in a modern healthcare strategy meeting."],
  ["/images/about/founder-vision.jpg", photoLibrary.boardroomConversation, "Founder-level healthcare strategy conversation in a premium office setting."],
  ["/images/medical-tourism/patient-consultation.jpg", photoLibrary.consultationLead, "International patient consultation focused on treatment options and travel planning."],
  ["/images/medical-tourism/airport-assistance.jpg", photoLibrary.wheelchairTravel, "Healthcare support agent meeting an international patient during arrival support."],
  ["/images/medical-tourism/visa-support.jpg", photoLibrary.travelSuitcase, "Travel support specialist reviewing visa and medical travel documents."],
  ["/images/medical-tourism/hospital-arrival.jpg", photoLibrary.wheelchairHospital, "International patient arriving at a premium hospital with assistance support."],
  ["/images/medical-tourism/accommodation-support.jpg", photoLibrary.familyConsultation, "Patient family discussing accommodation and recovery support near a treatment facility."],
  ["/images/medical-tourism/medical-reports-review.jpg", photoLibrary.reportReview, "Medical specialists reviewing reports and diagnostics for a treatment case."],
  ["/images/medical-tourism/treatment-support.jpg", photoLibrary.surgeryTeam, "Hospital team coordinating surgery and treatment preparation for an international patient."],
  ["/images/hospital-partnerships/partnership-meeting.jpg", photoLibrary.executiveMeeting, "Hospital leaders in a formal international healthcare partnership discussion."],
  ["/images/hospital-partnerships/partner-hospital-01.jpg", photoLibrary.hospitalExteriorWhite, "Premium hospital building representing potential institutional collaboration."],
  ["/images/hospital-partnerships/doctor-collaboration.jpg", photoLibrary.reportReview, "Doctors in clinical discussion for cross-border specialist collaboration."],
  ["/images/hospital-partnerships/healthcare-conference.jpg", photoLibrary.healthcareDelegation, "International healthcare conference supporting partnership development and institutional networking."],
  ["/images/hospital-partnerships/international-desk.jpg", photoLibrary.coordinatorReception, "Hospital international desk team coordinating patient referral and partnership workflows."],
  ["/images/international-patients/patient-coordinator.jpg", photoLibrary.coordinatorTablet, "Dedicated case manager assisting an international patient and family."],
  ["/images/international-patients/translator-support.jpg", photoLibrary.coordinatorDeskConsultation, "Translator and interpreter assisting an international healthcare consultation."],
  ["/images/international-patients/hospital-guidance.jpg", photoLibrary.hospitalWorkerCorridor, "International patient receiving in-hospital guidance and appointment support."],
  ["/images/international-patients/family-support.jpg", photoLibrary.familyConsultation, "Patient family receiving reassurance and treatment journey guidance from healthcare staff."],
  ["/images/international-patients/patient-success.jpg", photoLibrary.seniorPatientGuide, "Recovered patient celebrating a positive international healthcare experience."],
  ["/images/student-mobility/health-sciences-campus.jpg", photoLibrary.hospitalExteriorModern, "Modern health sciences campus representing international academic mobility opportunities."],
  ["/images/student-mobility/student-advising.jpg", photoLibrary.boardroomLaptops, "Professional student mobility advising session focused on healthcare pathways."],
  ["/images/student-mobility/document-review.jpg", photoLibrary.doctorTablet, "Admissions coordinator reviewing student documents for an international health sciences application."],
  ["/images/student-mobility/international-welcome.jpg", photoLibrary.travelSuitcase, "Students arriving for a healthcare-focused international mobility experience."],
  ["/images/blog/healthcare-news-01.jpg", photoLibrary.hospitalExteriorGlass, "Editorial healthcare news visual with hospital and specialist context."],
  ["/images/blog/healthcare-news-02.jpg", photoLibrary.consultationClipboard, "Editorial image representing medical tourism and international patient coordination updates."],
  ["/images/blog/cancer-breakthrough.jpg", photoLibrary.patientExam, "Advanced oncology consultation scene for editorial coverage of cancer treatment breakthroughs."],
  ["/images/blog/transplant-innovation.jpg", photoLibrary.surgeryRoom, "Specialist team in a transplant-focused hospital environment."],
  ["/images/blog/hospital-partnership-news.jpg", photoLibrary.executiveMeeting, "Hospital leadership meeting supporting editorial coverage of healthcare partnerships."],
  ["/images/blog/international-healthcare-events.jpg", photoLibrary.healthcareDelegation, "Editorial image from a premium international healthcare event or conference."],
  ["/images/contact/contact-desk.jpg", photoLibrary.coordinatorReception, "Professional healthcare contact desk ready to receive patient and hospital enquiries."],
  ["/images/contact/consultation-meeting.jpg", photoLibrary.coordinatorDeskConsultation, "Premium healthcare consultation meeting between MedPobeda representatives and stakeholders."],
  ["/images/contact/hospital-campus.jpg", photoLibrary.hospitalExteriorWhite, "Modern hospital campus representing MedPobeda's healthcare partner environment."],
  ["/images/contact/international-support.jpg", photoLibrary.followUpClipboard, "International healthcare support specialist helping a client with next steps."],
] as const;

export const premiumImageRegistry = buildRegistry(premiumImageEntries);
export const legacyImageRegistry = buildRegistry(legacyImageEntries);

const fallbackPremiumImage: ManagedImage = {
  src: photoLibrary.consultationLead,
  alt: "Premium healthcare consultation support.",
};

export function getPremiumImage(
  category: string,
  slug: string,
  fallbackAlt?: string,
): ManagedImage {
  const key = `${category}/${slug}`;
  const image = premiumImageRegistry[key] ?? fallbackPremiumImage;

  return {
    src: image.src,
    alt: fallbackAlt ?? image.alt,
  };
}

export function getPremiumImageSrc(category: string, slug: string) {
  return getPremiumImage(category, slug).src;
}

export function getLegacyImage(path: string, fallbackAlt?: string): ManagedImage {
  const image = legacyImageRegistry[path];

  if (!image) {
    return {
      src: path,
      alt: fallbackAlt ?? "Premium healthcare image.",
    };
  }

  return {
    src: image.src,
    alt: fallbackAlt ?? image.alt,
  };
}

export function getLegacyImageSrc(path: string) {
  return getLegacyImage(path).src;
}
