export type UzSeoFaq = {
  question: string;
  answer: string;
};

export type UzMedicalSeoPage = {
  slug: string;
  title: string;
  shortTitle: string;
  condition: string;
  specialty: string;
  procedure: string;
  audience: string;
  symptoms: string[];
  diagnostics: string[];
  treatments: string[];
  recoveryFocus: string;
  image: {
    src: string;
    filename: string;
    alt: string;
    caption: string;
    title: string;
  };
  faqs: UzSeoFaq[];
};

type Seed = [
  slug: string,
  title: string,
  condition: string,
  specialty: string,
  procedure: string,
  symptoms: string,
  diagnostics: string,
  treatments: string,
  recoveryFocus: string,
];

const seeds: Seed[] = [
  ["hindistonda-davolanish", "Hindistonda davolanish: O‘zbekistonlik bemorlar uchun qo‘llanma", "murakkab va rejalashtirilgan kasalliklar", "xalqaro tibbiyot", "individual davolash dasturi", "uzoq davom etuvchi shikoyatlar|mahalliy davolashdan yetarli natija bo‘lmasligi|ikkinchi tibbiy fikrga ehtiyoj", "tibbiy hujjatlarni ko‘rib chiqish|mutaxassis konsultatsiyasi|zarur laborator va tasviriy tekshiruvlar", "konservativ davolash|jarrohlik muolajasi|reabilitatsiya dasturi", "xavfsiz uyga qaytish va nazorat rejasiga rioya qilish"],
  ["saratonni-hindistonda-davolash", "Saratonni Hindistonda davolash: diagnostika va terapiya", "saraton", "onkologiya", "multidisiplinar onkologik davolash", "sababsiz vazn yo‘qotish|uzoq saqlanadigan og‘riq|g‘ayrioddiy shish yoki qon ketishi", "biopsiya va gistologiya|PET-KT yoki MRT|molekulyar va immunogistokimyoviy tahlil", "jarrohlik|kimyoterapiya va maqsadli terapiya|radioterapiya yoki immunoterapiya", "nojo‘ya ta’sirlarni boshqarish va bosqichma-bosqich faollashish"],
  ["yurak-operatsiyasi-hindiston", "Hindistonda yurak operatsiyasi: tekshiruvdan tiklanishgacha", "yurak-qon tomir kasalliklari", "kardiologiya va kardiojarrohlik", "yurak operatsiyasi", "ko‘krakdagi bosuvchi og‘riq|nafas qisishi|tez charchash yoki yurak urishining buzilishi", "EKG va EхоKG|koronar angiografiya|qon tahlillari va yurak xavfini baholash", "angioplastika va stentlash|koronar shuntlash|klapan operatsiyasi", "kardio-reabilitatsiya va yurak uchun sog‘lom odatlar"],
  ["ivf-hindiston", "Hindistonda IVF: bepushtlikni davolash bo‘yicha qo‘llanma", "bepushtlik", "reproduktologiya", "IVF va embrion ko‘chirish", "bir yil davomida homiladorlik bo‘lmasligi|hayz siklining buzilishi|oldingi homila yo‘qotishlari", "gormonal tekshiruvlar|ultratovush va tuxumdon zaxirasi|spermogramma va genetik maslahat", "ovulyatsiyani rag‘batlantirish|IVF yoki ICSI|embrion ko‘chirish", "dori jadvali, hissiy qo‘llab-quvvatlash va kuzatuv"],
  ["tizza-almashtirish", "Hindistonda tizza bo‘g‘imini almashtirish", "tizza artrozi", "ortopediya", "tizza endoprotezlash", "yurishda kuchayadigan og‘riq|bo‘g‘im qotishi|zinadan chiqishda qiyinchilik", "rentgen|MRT zarur bo‘lsa|ortopedik va anesteziologik baholash", "dori va fizioterapiya|qisman protezlash|to‘liq tizza endoprotezlash", "erta yurish, fizioterapiya va bo‘g‘im harakatini tiklash"],
  ["buyrak-transplantatsiyasi", "Hindistonda buyrak transplantatsiyasi: bemor yo‘li", "yakuniy bosqichdagi buyrak yetishmovchiligi", "nefrologiya va transplantologiya", "buyrak transplantatsiyasi", "dializga ehtiyoj|shish va holsizlik|buyrak faoliyatining keskin pasayishi", "buyrak funksiyasi tahlillari|donor va retsipiyent mosligi|infeksiya hamda yurak xavfini tekshirish", "gemodializ yoki peritoneal dializ|tirik donordan transplantatsiya|operatsiyadan keyingi immunosupressiya", "dori intizomi, infeksiyadan saqlanish va muntazam tahlil"],
  ["jigar-transplantatsiyasi", "Hindistonda jigar transplantatsiyasi: to‘liq qo‘llanma", "og‘ir jigar yetishmovchiligi", "gepatologiya va transplantologiya", "jigar transplantatsiyasi", "sariqlik|qorin bo‘shlig‘ida suyuqlik|hushyorlik o‘zgarishi yoki qon ketishi", "jigar funksiyasi tahlillari|KT yoki MRT|donor mosligi va transplant komissiyasi bahosi", "kasallik sababini davolash|tirik donor transplantatsiyasi|operatsiyadan keyingi immunosupressiya", "jigar ko‘rsatkichlari nazorati, ovqatlanish va dori intizomi"],
  ["neyroxirurgiya", "Hindistonda neyroxirurgiya: miya va umurtqa davolash", "miya, nerv va umurtqa kasalliklari", "neyroxirurgiya", "neyroxirurgik muolaja", "kuchli yoki yangi bosh og‘rig‘i|qo‘l-oyoq kuchsizligi|muvozanat yoki sezgi buzilishi", "nevrologik ko‘rik|MRT yoki KT|neyrofiziologik tekshiruvlar", "mikrojarrohlik|endoskopik operatsiya|stereotaktik yoki funksional muolaja", "nevrologik reabilitatsiya va xavfsiz faollashish"],
  ["onkologiya", "Hindistonda onkologiya: saraton bo‘yicha kompleks yordam", "turli xil xavfli o‘smalar", "onkologiya", "shaxsiylashtirilgan saraton terapiyasi", "sababsiz vazn kamayishi|bitmaydigan yara yoki shish|uzoq davom etadigan holsizlik", "gistopatologiya tekshiruvi|bosqichlash uchun tasviriy tekshiruv|biomarker tahlillari", "jarrohlik onkologiyasi|tizimli terapiya|radiatsion onkologiya", "ovqatlanish, simptom nazorati va kuzatuv tekshiruvlari"],
  ["kardiologiya", "Hindistonda kardiologiya: yurak diagnostikasi va davolash", "yurak va qon tomir kasalliklari", "kardiologiya", "kardiologik davolash", "ko‘krak og‘rig‘i|nafas qisishi|yurak urishining tezlashishi", "EKG|EхоKG va stress-test|angiografiya zarur bo‘lsa", "dori bilan davolash|interventsion kardiologiya|kardiojarrohlik", "yurak reabilitatsiyasi va xavf omillarini nazorat qilish"],
  ["kokrak-saratoni-hindistonda", "Ko‘krak saratonini Hindistonda davolash", "ko‘krak saratoni", "onkologiya va mammologiya", "ko‘krak saratonini kompleks davolash", "ko‘krakda tugun|teri yoki so‘rg‘ich o‘zgarishi|qo‘ltiq ostida shish", "mammografiya va ultratovush|biopsiya|retseptor va HER2 tahlili", "ko‘krakni saqlovchi jarrohlik yoki mastektomiya|tizimli terapiya|radioterapiya", "qo‘l limfedemasini oldini olish va onkologik kuzatuv"],
  ["opka-saratoni-hindistonda", "O‘pka saratonini Hindistonda davolash", "o‘pka saratoni", "torakal onkologiya", "o‘pka saratonini kompleks davolash", "uzoq davom etuvchi yo‘tal|qon tupurish|nafas qisishi yoki vazn yo‘qotish", "ko‘krak KT|bronxoskopiya va biopsiya|molekulyar profil", "jarrohlik|kimyoterapiya yoki immunoterapiya|maqsadli terapiya va radioterapiya", "nafas mashqlari, ovqatlanish va simptomlarni nazorat qilish"],
  ["prostata-saratoni-hindistonda", "Prostata saratonini Hindistonda davolash", "prostata saratoni", "uroonkologiya", "prostata saratoni terapiyasi", "siydik chiqarish qiyinlashishi|tez-tez siyish|tos yoki suyak og‘rig‘i", "PSA tahlili|prostata MRT|biopsiya va bosqichlash", "faol kuzatuv|robotik prostatektomiya|radioterapiya va gormonal terapiya", "siydik nazorati va jinsiy salomatlik reabilitatsiyasi"],
  ["bachadon-boyni-saratoni", "Bachadon bo‘yni saratonini Hindistonda davolash", "bachadon bo‘yni saratoni", "ginekologik onkologiya", "bachadon bo‘yni saratoni terapiyasi", "hayz oralig‘ida qon ketishi|jinsiy aloqadan keyin qon ketishi|tos sohasida og‘riq", "ginekologik ko‘rik|biopsiya|MRT yoki PET-KT bilan bosqichlash", "jarrohlik|kimyo-radioterapiya|braxiterapiya", "tos salomatligi, ovqatlanish va rejalashtirilgan nazorat"],
  ["oshqozon-saratoni-hindistonda", "Oshqozon saratonini Hindistonda davolash", "oshqozon saratoni", "gastrointestinal onkologiya", "oshqozon saratoni terapiyasi", "tez to‘yish|qorin yuqorisida og‘riq|vazn yo‘qotish yoki kamqonlik", "gastroskopiya va biopsiya|KT yoki PET-KT|laparoskopik bosqichlash zarur bo‘lsa", "gastrektomiya|kimyoterapiya|maqsadli yoki immunoterapiya", "kichik porsiyalarda ovqatlanish va vazn nazorati"],
  ["ichak-saratoni-hindistonda", "Yo‘g‘on ichak saratonini Hindistonda davolash", "kolorektal saraton", "gastrointestinal onkologiya", "kolorektal saraton terapiyasi", "ich kelish odatining o‘zgarishi|najasda qon|qorin og‘rig‘i yoki kamqonlik", "kolonoskopiya va biopsiya|KT yoki MRT|molekulyar tahlil", "laparoskopik yoki robotik jarrohlik|kimyoterapiya|rektal saratonda radioterapiya", "ichak faoliyati, stoma parvarishi zarur bo‘lsa va kuzatuv"],
  ["qon-saratoni-hindistonda", "Qon saratonini Hindistonda davolash", "leykemiya, limfoma va mieloma", "gematologiya", "gematologik saraton terapiyasi", "tez-tez infeksiya|ko‘karish yoki qon ketishi|limfa tugunlari kattalashishi", "umumiy qon tahlili|suyak ko‘migi tekshiruvi|oqim sitometriyasi va genetik tahlil", "kimyoterapiya|maqsadli yoki immunoterapiya|ildiz hujayra transplantatsiyasi", "infeksiyani oldini olish va qon ko‘rsatkichlarini kuzatish"],
  ["suyak-iligi-transplantatsiyasi", "Hindistonda suyak iligi transplantatsiyasi", "qon va suyak iligi kasalliklari", "gematologiya va transplantologiya", "gematopoetik ildiz hujayra transplantatsiyasi", "og‘ir kamqonlik|takroriy infeksiyalar|davolashga javob bermayotgan qon kasalligi", "suyak ko‘migi tahlili|HLA moslik|yurak, o‘pka va infeksiya skriningi", "autolog transplantatsiya|allogen transplantatsiya|qo‘llab-quvvatlovchi davolash", "himoyalangan muhit, infeksiya profilaktikasi va qon nazorati"],
  ["miya-osmasi-operatsiyasi", "Hindistonda miya o‘smasi operatsiyasi", "miya o‘smalari", "neyroonkologiya", "miya o‘smasini jarrohlik yo‘li bilan davolash", "yangi kuchli bosh og‘rig‘i|tutqanoq|ko‘rish, nutq yoki harakat o‘zgarishi", "kontrastli MRT|nevrologik baholash|funksional xaritalash zarur bo‘lsa", "mikrojarrohlik rezeksiya|endoskopik jarrohlik|radioterapiya va tizimli terapiya", "nevrologik funksiyalarni tiklash va tutqanoq nazorati"],
  ["umurtqa-operatsiyasi-hindiston", "Hindistonda umurtqa operatsiyasi", "umurtqa pog‘onasi kasalliklari", "spinal neyroxirurgiya va ortopediya", "umurtqa operatsiyasi", "bel yoki bo‘yin og‘rig‘i|qo‘l-oyoq uvishishi|mushak kuchsizligi", "MRT|rentgen yoki KT|nevrologik va funksional baholash", "minimal invaziv disk operatsiyasi|dekompressiya|stabilizatsiya va fiksatsiya", "to‘g‘ri harakat, fizioterapiya va belni himoya qilish"],
  ["skolioz-davolash-hindiston", "Skoliozni Hindistonda davolash", "skolioz", "umurtqa ortopediyasi", "skoliozni tuzatish", "yelka balandligining farqi|umurtqa qiyshayishi|og‘riq yoki nafas cheklanishi", "tik holatda rentgen|MRT zarur bo‘lsa|o‘sish va o‘pka funksiyasini baholash", "kuzatuv va korset|fizioterapiya|jarrohlik korreksiya", "gavda muvozanati, nafas va harakat reabilitatsiyasi"],
  ["son-bogimini-almashtirish", "Hindistonda son bo‘g‘imini almashtirish", "son bo‘g‘imi artrozi yoki nekrozi", "ortopediya", "son endoprotezlash", "chov sohasidagi og‘riq|oqsoqlanish|harakat hajmining kamayishi", "rentgen|MRT ayrim holatlarda|operatsiya oldi umumiy baholash", "dori va fizioterapiya|sonni saqlovchi muolaja|to‘liq endoprotezlash", "erta yurish, tromboz profilaktikasi va fizioterapiya"],
  ["robotik-jarrohlik-hindiston", "Hindistonda robotik jarrohlik", "robotik usul mos keladigan jarrohlik kasalliklari", "minimal invaziv jarrohlik", "robot yordamidagi operatsiya", "kasallikka xos davomli alomatlar|ochiq operatsiya xavfi haqida xavotir|mutaxassis jarroh bahosiga ehtiyoj", "tasviriy tekshiruvlar|laborator tahlillar|jarrohlik va anesteziologik baholash", "robotik jarrohlik|laparoskopik jarrohlik|ochiq operatsiya zarur bo‘lsa", "kichik kesmalar parvarishi va bosqichma-bosqich faollashish"],
  ["laparoskopik-jarrohlik", "Hindistonda laparoskopik jarrohlik", "minimal invaziv usul bilan davolanadigan kasalliklar", "umumiy jarrohlik", "laparoskopik operatsiya", "qorin sohasidagi takroriy og‘riq|hazm yoki organ faoliyati buzilishi|jarrohlik tashxisi", "ultratovush yoki KT|qon tahlillari|anesteziolog ko‘rigi", "laparoskopik operatsiya|robotik yondashuv|ochiq jarrohlik zarur bo‘lsa", "kesma parvarishi, ovqatlanish va erta yurish"],
  ["bariatrik-jarrohlik-hindiston", "Hindistonda bariatrik jarrohlik va vazn kamaytirish", "og‘ir semizlik", "bariatrik va metabolik jarrohlik", "vazn kamaytirish operatsiyasi", "yuqori tana vazni|2-tur diabet yoki uyqu apnoesi|parhez bilan barqaror natija bo‘lmasligi", "BMI va tana tarkibi|endokrin tahlillar|ovqatlanish va psixologik baholash", "sleeve gastrektomiya|gastrik bypass|tibbiy vazn boshqaruvi", "yangi ovqatlanish tartibi, vitaminlar va jismoniy faollik"],
  ["diabet-davolash-hindiston", "Qandli diabetni Hindistonda davolash", "qandli diabet", "endokrinologiya", "kompleks diabet nazorati", "chanqoq va ko‘p siyish|vazn o‘zgarishi|qand ko‘rsatkichlarining beqarorligi", "och qoringa glyukoza va HbA1c|buyrak va ko‘z skriningi|yurak-qon tomir xavfi", "ovqatlanish va jismoniy faollik|tabletkalar|insulin yoki texnologik monitoring", "qandni mustaqil nazorat qilish va asoratlar profilaktikasi"],
  ["qalqonsimon-bez-davolash", "Qalqonsimon bez kasalliklarini Hindistonda davolash", "qalqonsimon bez kasalliklari", "endokrinologiya va endokrin jarrohlik", "qalqonsimon bezni davolash", "vazn va yurak urishi o‘zgarishi|bo‘yinda shish|holsizlik yoki issiqqa-sovuqqa sezgirlik", "TSH va qalqonsimon bez gormonlari|ultratovush|ingichka ignali biopsiya zarur bo‘lsa", "dori bilan davolash|radioyod|jarrohlik", "gormon ko‘rsatkichlarini nazorat qilish va dori dozasini moslash"],
  ["bolalar-kardiojarrohligi", "Hindistonda bolalar kardiojarrohligi", "tug‘ma yurak nuqsonlari", "bolalar kardiologiyasi", "bolalar yurak operatsiyasi", "emishda yoki harakatda tez charchash|ko‘karish|vazn yig‘ishning sustligi", "bolalar EхоKG|EKG va kislorod darajasi|KT, MRT yoki kateterizatsiya zarur bo‘lsa", "kateter orqali muolaja|ochiq yurak operatsiyasi|bosqichli davolash", "ota-ona uchun parvarish rejasi va bolaning o‘sishini kuzatish"],
  ["tugma-yurak-nuqsoni", "Tug‘ma yurak nuqsonini Hindistonda davolash", "tug‘ma yurak nuqsoni", "bolalar kardiologiyasi va kardiojarrohlik", "yurak nuqsonini tuzatish", "ko‘karish|tez nafas olish|ovqatlanishda charchash", "EхоKG|pulsoksimetriya|yurak KT/MRT yoki kateterizatsiya", "kuzatuv va dori|kateter muolajasi|jarrohlik korreksiya", "ovqatlanish, yara parvarishi va kardiolog nazorati"],
  ["bolalar-onkologiyasi", "Hindistonda bolalar onkologiyasi", "bolalardagi saraton kasalliklari", "pediatrik onkologiya", "bolalar saratonini davolash", "uzoq isitma yoki holsizlik|sababsiz ko‘karish|shish yoki suyak og‘rig‘i", "qon va suyak ko‘migi tahlili|tasviriy tekshiruv|biopsiya va molekulyar baholash", "bolalarga mos kimyoterapiya|jarrohlik|radioterapiya yoki transplantatsiya", "o‘sish, ovqatlanish, infeksiya himoyasi va psixologik yordam"],
  ["bolalar-neyroxirurgiyasi", "Hindistonda bolalar neyroxirurgiyasi", "bolalar miya va umurtqa kasalliklari", "pediatrik neyroxirurgiya", "bolalar neyroxirurgik muolajasi", "bosh aylanasining tez o‘sishi|tutqanoq|harakat yoki rivojlanishdagi o‘zgarish", "bolalar nevrologik ko‘rigi|MRT yoki KT|rivojlanish va anesteziya bahosi", "endoskopik muolaja|mikrojarrohlik|shunt yoki rekonstruktiv operatsiya", "rivojlanish reabilitatsiyasi va oilaviy parvarish"],
  ["epilepsiya-davolash-hindiston", "Epilepsiyani Hindistonda davolash", "epilepsiya", "nevrologiya va epileptologiya", "epilepsiyani kompleks davolash", "takroriy tutqanoq|qisqa hush yo‘qolishi|g‘ayrioddiy harakat yoki sezgi epizodlari", "video-EEG|epilepsiya protokolidagi MRT|neyropsixologik baholash", "tutqanoqqa qarshi dorilar|ketogen parhez ayrim bolalarda|epilepsiya jarrohligi", "tutqanoq xavfsizligi, dori intizomi va uyqu tartibi"],
  ["parkinson-davolash-hindiston", "Parkinson kasalligini Hindistonda davolash", "Parkinson kasalligi", "harakat buzilishlari nevrologiyasi", "Parkinson terapiyasi", "titrash|harakatning sekinlashishi|mushak qotishi va muvozanat buzilishi", "nevrologik ko‘rik|dori javobini baholash|MRT va kognitiv testlar zarur bo‘lsa", "dori terapiyasi|fizioterapiya va nutq terapiyasi|chuqur miya stimulyatsiyasi", "harakat, yiqilishning oldini olish va kundalik faoliyat"],
  ["chuqur-miya-stimulyatsiyasi", "Hindistonda chuqur miya stimulyatsiyasi (DBS)", "dori bilan yetarli boshqarilmaydigan harakat buzilishi", "funksional neyroxirurgiya", "chuqur miya stimulyatsiyasi", "dori ta’sirining qisqarishi|kuchli titrash|diskineziya yoki harakat cheklanishi", "harakat mutaxassisi bahosi|dori sinovi|MRT va neyropsixologik tekshiruv", "DBS implantatsiyasi|qurilmani dasturlash|dori va reabilitatsiyani moslash", "stimulyator sozlamalari va nevrologik kuzatuv"],
  ["insultdan-keyingi-reabilitatsiya", "Hindistonda insultdan keyingi reabilitatsiya", "insult oqibatlari", "nevrologik reabilitatsiya", "insultdan keyingi tiklanish dasturi", "qo‘l-oyoq kuchsizligi|nutq yoki yutish qiyinligi|muvozanat va xotira buzilishi", "nevrologik baholash|yutish va nutq testi|harakat hamda kundalik faoliyat bahosi", "fizioterapiya|ergoterapiya|nutq va yutish terapiyasi", "mustaqillikni oshirish va qayta insult profilaktikasi"],
  ["multiple-skleroz-davolash", "Ko‘p o‘choqli sklerozni Hindistonda davolash", "ko‘p o‘choqli skleroz", "neyroimmunologiya", "kasallikni o‘zgartiruvchi terapiya", "ko‘rish xiralashishi|uvishish yoki kuchsizlanish|muvozanat va kuchli charchoq", "bosh va orqa miya MRT|likvor tekshiruvi zarur bo‘lsa|nevrologik funksional baholash", "xurujni davolash|kasallikni o‘zgartiruvchi dorilar|reabilitatsiya", "charchoqni boshqarish, jismoniy faollik va monitoring"],
  ["endometrioz-davolash-hindiston", "Endometriozni Hindistonda davolash", "endometrioz", "ginekologiya", "endometriozni kompleks davolash", "og‘riqli hayz|surunkali tos og‘rig‘i|homilador bo‘lish qiyinligi", "ginekologik ultratovush|MRT ayrim holatlarda|fertillik bahosi", "og‘riq va gormonal terapiya|laparoskopik eksiziya|fertillik muolajalari", "og‘riq nazorati, tos fizioterapiyasi va reproduktiv reja"],
  ["bachadon-miomasi-hindiston", "Bachadon miomasini Hindistonda davolash", "bachadon miomasi", "ginekologiya", "miomani davolash", "ko‘p hayz qon ketishi|tosda bosim|kamqonlik yoki bepushtlik", "ultratovush|MRT zarur bo‘lsa|qon va fertilitet bahosi", "dori|miomektomiya yoki embolizatsiya|gisterektomiya tanlangan holatda", "qon ko‘rsatkichlari, yara parvarishi va reproduktiv reja"],
  ["tuxumdon-kistasi-operatsiyasi", "Hindistonda tuxumdon kistasi operatsiyasi", "tuxumdon kistalari", "ginekologiya", "tuxumdon kistasini olib tashlash", "tos og‘rig‘i|qorin dam bo‘lishi|hayz sikli o‘zgarishi", "transvaginal ultratovush|o‘sma markerlari zarur bo‘lsa|MRT yoki KT", "kuzatuv|laparoskopik sistektomiya|onkologik jarrohlik shubhali holatda", "fertillikni asrash va operatsiyadan keyingi kuzatuv"],
  ["erkaklar-bepushtligi-hindiston", "Erkaklar bepushtligini Hindistonda davolash", "erkaklar bepushtligi", "andrologiya va reproduktologiya", "erkak fertilitetini davolash", "homiladorlikning kechikishi|spermogramma o‘zgarishi|varikotsele yoki gormonal belgilar", "takroriy spermogramma|gormon va genetik tahlil|ultratovush zarur bo‘lsa", "turmush tarzini tuzatish|varikotsele operatsiyasi|ICSI uchun sperm olish", "reproduktiv reja va davolash natijalarini qayta baholash"],
  ["ayollar-bepushtligi-hindiston", "Ayollar bepushtligini Hindistonda davolash", "ayollar bepushtligi", "reproduktologiya", "ayol fertilitetini davolash", "homiladorlik bo‘lmasligi|hayz notekisligi|tos kasalliklari tarixi", "ovulyatsiya va gormonlar|tuxumdon zaxirasi|bachadon va naylarni baholash", "ovulyatsiya induksiyasi|jarrohlik tuzatish|IUI yoki IVF", "sikl monitoringi, hissiy yordam va homiladorlik kuzatuvi"],
  ["kornea-transplantatsiyasi", "Hindistonda shox parda transplantatsiyasi", "shox parda xiralashuvi yoki zarari", "oftalmologiya", "kornea transplantatsiyasi", "ko‘rish xiralashishi|yorug‘likdan bezovtalik|kornea chandiqi yoki shishi", "ko‘z biomikroskopiyasi|kornea topografiyasi|endotelial hujayra bahosi", "DMEK yoki DSAEK|DALK|to‘liq qalinlikdagi keratoplastika", "ko‘z tomchilari, rad etilish belgilarini bilish va nazorat"],
  ["katarakta-operatsiyasi-hindiston", "Hindistonda katarakta operatsiyasi", "katarakta", "oftalmologiya", "fakoemulsifikatsiya va linza implantatsiyasi", "xira ko‘rish|kechasi yaltirash|ranglarni xira ko‘rish", "ko‘rish o‘tkirligi|ko‘z biomikroskopiyasi|sun’iy linza uchun biometrik o‘lchov", "fakoemulsifikatsiya|monofokal yoki premium linza|qo‘shimcha ko‘z kasalligini davolash", "tomchilar, ko‘zni himoya qilish va ko‘rishni tekshirish"],
  ["lasik-hindiston", "Hindistonda LASIK ko‘z operatsiyasi", "refraksiya nuqsonlari", "refraktiv oftalmologiya", "LASIK yoki ko‘rishni lazer bilan tuzatish", "ko‘zoynakka bog‘liqlik|miopiya|gipermetropiya yoki astigmatizm", "refraksiya o‘lchovi|kornea topografiyasi va qalinligi|quruq ko‘z bahosi", "LASIK|SMILE|PRK yoki implantatsion linza", "ko‘z tomchilari, ekran tanaffusi va korneani himoya qilish"],
  ["retina-davolash-hindiston", "Hindistonda retina kasalliklarini davolash", "to‘r parda kasalliklari", "vitreoretinal oftalmologiya", "retina terapiyasi", "ko‘z oldida chaqnash yoki nuqtalar|ko‘rishning egilishi|to‘satdan ko‘rish pasayishi", "kengaytirilgan ko‘z tubi ko‘rigi|OCT|fluorestsein angiografiya yoki ultratovush", "intravitreal ineksiya|retina lazeri|vitrektomiya", "ko‘rish monitoringi va favqulodda belgilarni tanish"],
  ["koklear-implant-hindiston", "Hindistonda koxlear implant", "og‘ir eshitish qobiliyati yo‘qolishi", "otologiya va audiologiya", "koxlear implantatsiya", "nutqni tushunmaslik|eshitish apparatidan kam foyda|bolada nutq rivoji kechikishi", "audiometriya|eshitish apparati sinovi|KT/MRT va nutq bahosi", "koxlear implant|implantni sozlash|eshitish-nutq reabilitatsiyasi", "qurilmani xaritalash va muntazam audiologik mashg‘ulot"],
  ["eshitishni-tiklash-hindiston", "Hindistonda eshitishni tiklash davolashlari", "eshitish pasayishi", "LOR va audiologiya", "eshitishni reabilitatsiya qilish", "suhbatni tushunish qiyinligi|quloqda shovqin|ovozni balandlatishga ehtiyoj", "audiometriya va timpanometriya|LOR ko‘rigi|KT yoki MRT zarur bo‘lsa", "eshitish apparati|o‘rta quloq operatsiyasi|implantatsion qurilmalar", "eshitish moslamasiga moslashish va nutqni anglash mashqlari"],
  ["sinus-operatsiyasi-hindiston", "Hindistonda endoskopik sinus operatsiyasi", "surunkali sinusit", "rinologiya", "endoskopik sinus jarrohligi", "burun bitishi|yuzda bosim|hid bilishning pasayishi", "LOR endoskopiyasi|sinuslar KT|allergiya bahosi zarur bo‘lsa", "burun yuvish va dorilar|endoskopik sinus operatsiyasi|poliplarni davolash", "burun parvarishi, yuvish va LOR nazorati"],
  ["buyrak-toshi-davolash", "Buyrak toshini Hindistonda davolash", "buyrak va siydik yo‘li toshlari", "urologiya", "buyrak toshini olib tashlash", "belda kuchli sanchiqli og‘riq|siydikda qon|ko‘ngil aynishi yoki isitma", "kontrastsiz KT|siydik va qon tahlili|tosh tarkibi va metabolik baholash", "ESWL|ureteroskopiya|PCNL", "suyuqlik ichish, tosh tahlili va qaytalanish profilaktikasi"],
  ["prostata-adenomasi-operatsiyasi", "Prostata adenomasini Hindistonda davolash", "prostata bezining yaxshi sifatli kattalashuvi", "urologiya", "prostata adenomasini operativ davolash", "siydik oqimining sustligi|kechasi tez siyish|siydik to‘liq chiqmasligi", "PSA va siydik tahlili|ultratovush va qoldiq siydik|urofloumetriya", "dori|HoLEP yoki TURP|robotik oddiy prostatektomiya katta bezda", "kateter parvarishi, suyuqlik va siydik nazorati"],
  ["siydik-pufagi-saratoni", "Siydik pufagi saratonini Hindistonda davolash", "siydik pufagi saratoni", "uroonkologiya", "siydik pufagi saratoni terapiyasi", "og‘riqsiz siydikda qon|tez siyish|tos yoki bel og‘rig‘i", "sistoskopiya va TURBT|KT urografiya|gistologik bosqichlash", "endoskopik rezeksiya va pufak ichiga terapiya|sistektomiya|kimyoterapiya yoki immunoterapiya", "siydik yo‘li parvarishi va onkologik kuzatuv"],
  ["jigar-saratoni-hindiston", "Jigar saratonini Hindistonda davolash", "jigar saratoni", "gepatobiliar onkologiya", "jigar o‘smasi terapiyasi", "qorin yuqori o‘ngida og‘riq|vazn kamayishi|sariqlik yoki qorin shishi", "uch fazali KT yoki MRT|AFP va jigar tahlillari|biopsiya tanlangan holatda", "rezeksiya|ablatsiya yoki embolizatsiya|transplantatsiya yoki tizimli terapiya", "jigar funksiyasi, ovqatlanish va tasviriy kuzatuv"],
  ["oshqozon-osti-bezi-saratoni", "Oshqozon osti bezi saratonini Hindistonda davolash", "oshqozon osti bezi saratoni", "gastrointestinal onkologiya", "pankreas saratoni terapiyasi", "sariqlik|orqaga tarqaluvchi qorin og‘rig‘i|vazn kamayishi", "pankreas protokolidagi KT|endoskopik ultratovush va biopsiya|CA 19-9", "Whipple yoki boshqa rezeksiya|kimyoterapiya|radioterapiya tanlangan holatda", "hazm fermentlari, qand nazorati va ovqatlanish"],
  ["qizilongach-saratoni", "Qizilo‘ngach saratonini Hindistonda davolash", "qizilo‘ngach saratoni", "torakal va gastrointestinal onkologiya", "qizilo‘ngach saratoni terapiyasi", "yutish qiyinligi|vazn yo‘qotish|ko‘krak ortida noqulaylik", "endoskopiya va biopsiya|PET-KT|endoskopik ultratovush", "endoskopik rezeksiya erta bosqichda|kimyo-radioterapiya|ezofagektomiya", "yutish, nafas va ovqatlanish reabilitatsiyasi"],
  ["ogiz-bosh-boyni-saratoni", "Og‘iz, bosh va bo‘yin saratonini Hindistonda davolash", "bosh va bo‘yin saratoni", "bosh-bo‘yin onkologiyasi", "bosh va bo‘yin o‘smasi terapiyasi", "bitmaydigan og‘iz yarasi|bo‘yinda tugun|ovoz yoki yutish o‘zgarishi", "LOR endoskopiyasi|biopsiya|KT, MRT yoki PET-KT", "jarrohlik va rekonstruksiya|radioterapiya|tizimli terapiya", "nutq, yutish, og‘iz parvarishi va ovqatlanish"],
  ["qalqonsimon-bez-saratoni", "Qalqonsimon bez saratonini Hindistonda davolash", "qalqonsimon bez saratoni", "endokrin onkologiya", "qalqonsimon bez saratoni terapiyasi", "bo‘yinda tugun|ovoz bo‘g‘ilishi|yutish qiyinligi", "ultratovush|ingichka ignali biopsiya|TSH va zarur molekulyar tahlil", "qalqonsimon bez jarrohligi|radioyod|gormon bostiruvchi terapiya", "kalsiy va gormon nazorati, ovoz hamda onkologik kuzatuv"],
  ["limfoma-davolash-hindiston", "Limfomani Hindistonda davolash", "Xodjkin va no-Xodjkin limfoma", "gematoonkologiya", "limfoma terapiyasi", "og‘riqsiz limfa tuguni|kechasi terlash|isitma yoki vazn kamayishi", "to‘liq tugun biopsiyasi|PET-KT|suyak ko‘migi va molekulyar testlar zarur bo‘lsa", "kimyo-immunoterapiya|radioterapiya tanlangan holatda|hujayraviy yoki transplant terapiya", "infeksiya profilaktikasi va PET asosidagi kuzatuv"],
  ["leykoz-davolash-hindiston", "Leykozni Hindistonda davolash", "o‘tkir yoki surunkali leykoz", "gematoonkologiya", "leykoz terapiyasi", "tez charchash|isitma va infeksiya|ko‘karish yoki qon ketishi", "qon surtmasi|suyak ko‘migi|oqim sitometriyasi va sitogenetika", "kimyoterapiya|maqsadli terapiya|ildiz hujayra transplantatsiyasi", "qon ko‘rsatkichlari, infeksiya himoyasi va uzoq kuzatuv"],
  ["mieloma-davolash-hindiston", "Ko‘p sonli mielomani Hindistonda davolash", "ko‘p sonli mieloma", "gematoonkologiya", "mieloma terapiyasi", "suyak og‘rig‘i|kamqonlik va holsizlik|buyrak funksiyasi pasayishi", "oqsil elektroforezi va erkin yengil zanjir|suyak ko‘migi|PET-KT yoki butun tana tasviri", "kombinatsion dori terapiyasi|autolog transplantatsiya|suyakni himoya qiluvchi davolash", "buyrak, suyak salomatligi va kasallik markerlarini kuzatish"],
  ["car-t-terapiya-hindiston", "Hindistonda CAR-T hujayra terapiyasi", "ayrim qaytalangan qon saratonlari", "hujayraviy terapiya", "CAR-T hujayra terapiyasi", "oldingi davolashdan keyin kasallik qaytishi|davolashga chidamli limfoma yoki leykoz|hujayraviy terapiya bahosiga ehtiyoj", "kasallikni tasdiqlash va markerlar|organ funksiyasi va infeksiya skriningi|hujayra yig‘ish imkonini baholash", "leykaferez|limfodepleksiya|CAR-T infuziyasi va yaqin monitoring", "sitokin sindromi va nevrologik belgilar nazorati, uzoq kuzatuv"],
  ["proton-terapiya-hindiston", "Hindistonda proton terapiya", "aniq nurlantirish talab qiladigan o‘smalar", "radiatsion onkologiya", "proton nur terapiyasi", "o‘sma joyiga xos alomatlar|bolalarda radiatsiya yukini kamaytirish zarurati|qayta nurlantirish masalasi", "patologiyani tasdiqlash|rejalashtiruvchi KT va MRT|radiatsion onkolog konsiliumi", "proton terapiya|foton IMRT yoki VMAT|jarrohlik va tizimli terapiya kombinatsiyasi", "teri va charchoqni boshqarish, rejalashtirilgan tekshiruv"],
  ["gamma-pichoq-hindiston", "Hindistonda Gamma Knife radiojarrohligi", "kichik miya o‘smalari va tomir nuqsonlari", "stereotaktik radiojarrohlik", "Gamma Knife muolajasi", "bosh og‘rig‘i yoki tutqanoq|tasvirda aniqlangan kichik o‘choq|jarrohlik xavfi yuqori joylashuv", "yuqori aniqlikdagi MRT|neyroxirurg va radiatsion onkolog bahosi|doza rejalashtirish", "Gamma Knife|boshqa stereotaktik radioterapiya|mikrojarrohlik", "nevrologik belgilar va nazorat MRTlarini kuzatish"],
  ["kiber-pichoq-hindiston", "Hindistonda CyberKnife davolash", "stereotaktik davolashga mos o‘smalar", "stereotaktik radioterapiya", "CyberKnife muolajasi", "joylashuvga xos alomatlar|kichik yoki chegaralangan o‘sma|noinvaziv aniq davolash ehtiyoji", "KT va MRT/PET tasvirlari|biopsiya tasdig‘i|harakatni kuzatish va doza rejalash", "CyberKnife|SBRT|jarrohlik yoki boshqa radioterapiya", "qisqa muddatli nojo‘ya ta’sirlar va tasviriy kuzatuv"],
  ["angioplastika-hindiston", "Hindistonda koronar angioplastika va stent", "koronar arteriya torayishi", "interventsion kardiologiya", "angioplastika va stentlash", "ko‘krakda bosim|jismoniy harakatda nafas qisishi|yurak xuruji belgilari", "EKG va troponin|EхоKG|koronar angiografiya", "dori terapiyasi|angioplastika va stent|koronar shuntlash", "qonni suyultiruvchi dorilar, yurish va xavf omillari nazorati"],
  ["koronar-shuntlash-hindiston", "Hindistonda koronar shuntlash operatsiyasi", "ko‘p tomirli koronar kasallik", "kardiojarrohlik", "CABG koronar shuntlash", "ko‘krak og‘rig‘i|jismoniy zo‘riqishda nafas qisishi|angiografiyada ko‘p tomir torayishi", "koronar angiografiya|EхоKG|operatsiya xavfi va tomir manbasini baholash", "CABG|minimal invaziv shuntlash tanlangan holatda|gibrid revaskulyarizatsiya", "nafas mashqlari, ko‘krak suyagini asrash va kardio-reabilitatsiya"],
  ["yurak-klapani-almashtirish", "Hindistonda yurak klapanini almashtirish", "yurak klapani kasalligi", "kardiojarrohlik", "yurak klapanini ta’mirlash yoki almashtirish", "nafas qisishi|hushdan ketish|oyoqlarda shish yoki tez charchash", "EхоKG|yurak KT yoki kateterizatsiya|jarrohlik xavfi bahosi", "klapanni ta’mirlash|ochiq almashtirish|TAVI yoki boshqa kateter muolajasi", "antikoagulyatsiya zarur bo‘lsa, yurak nazorati va reabilitatsiya"],
  ["tavi-hindiston", "Hindistonda TAVI: aorta klapanini kateter orqali almashtirish", "og‘ir aorta stenozi", "interventsion kardiologiya", "TAVI muolajasi", "harakatda nafas qisishi|ko‘krak og‘rig‘i|hushdan ketish", "EхоKG|TAVI protokolidagi KT|koronar va umumiy xavf bahosi", "TAVI|ochiq aorta klapani operatsiyasi|simptom nazorati", "yurak ritmi, kirish joyi va jismoniy faollik nazorati"],
  ["aritmiya-ablatsiyasi-hindiston", "Hindistonda aritmiya ablatsiyasi", "yurak ritmi buzilishi", "elektrofiziologiya", "kateter ablatsiyasi", "yurak urishining tezlashishi|bosh aylanishi|hushdan ketish yoki holsizlik", "EKG va Holter|EхоKG|elektrofiziologik tekshiruv", "dori|kateter ablatsiyasi|kardiostimulyator yoki defibrillyator zarur bo‘lsa", "puls, kirish joyi va ritm qaytalanishini kuzatish"],
  ["yurak-transplantatsiyasi-hindiston", "Hindistonda yurak transplantatsiyasi", "yakuniy bosqich yurak yetishmovchiligi", "yurak transplantologiyasi", "yurak transplantatsiyasi", "tinch holatda nafas qisishi|takroriy shifoxonaga yotish|maksimal davoga qaramay og‘ir holsizlik", "EхоKG va yurak kateterizatsiyasi|o‘pka bosimi va organ funksiyasi|transplant komissiyasi bahosi", "optimal dori va qurilmalar|mexanik yurak yordami|yurak transplantatsiyasi", "immunosupressiya, biopsiya va infeksiya profilaktikasi"],
  ["dializ-hindiston", "Hindistonda dializ: sayohat va davolashni rejalashtirish", "buyrak yetishmovchiligi", "nefrologiya", "gemodializ", "shish|nafas qisishi|yuqori kaliy yoki uremiya belgilari", "kreatinin va elektrolitlar|dializ kirish yo‘lini baholash|infeksiya skriningi", "gemodializ|peritoneal dializ|transplantatsiya bahosi", "suyuqlik, parhez, kirish yo‘li va tahlillar nazorati"],
  ["pediatrik-buyrak-transplantatsiyasi", "Hindistonda bolalar buyrak transplantatsiyasi", "bolalardagi yakuniy buyrak yetishmovchiligi", "pediatrik nefrologiya", "bolalar buyrak transplantatsiyasi", "o‘sishning sustligi|shish yoki yuqori qon bosimi|dializ ehtiyoji", "buyrak funksiyasi va o‘sish bahosi|donor mosligi|infeksiya va immunologik skrining", "bolalarga mos dializ|tirik donor transplantatsiyasi|immunosupressiv terapiya", "o‘sish, dori dozasi, infeksiya va maktabga qaytish"],
  ["pediatrik-jigar-transplantatsiyasi", "Hindistonda bolalar jigar transplantatsiyasi", "bolalardagi og‘ir jigar kasalligi", "pediatrik gepatologiya", "bolalar jigar transplantatsiyasi", "uzoq sariqlik|o‘sishning sustligi|qorin shishi yoki qon ketishi", "jigar tahlillari|tasviriy tekshiruv|donor va bolaning transplant bahosi", "kasallikka xos davo|tirik donor transplantatsiyasi|operatsiyadan keyingi immunosupressiya", "ovqatlanish, o‘sish, dori va infeksiya nazorati"],
  ["crohn-kasalligi-hindiston", "Kron kasalligini Hindistonda davolash", "Kron kasalligi", "gastroenterologiya", "yallig‘lanishli ichak kasalligi terapiyasi", "uzoq diareya|qorin og‘rig‘i|vazn yo‘qotish yoki kamqonlik", "kolonoskopiya va biopsiya|MRT enterografiya|yallig‘lanish va ovqatlanish tahlillari", "yallig‘lanishga qarshi va immun dori|biologik terapiya|asoratlarda jarrohlik", "ovqatlanish, dori xavfsizligi va remissiya monitoringi"],
  ["yarali-kolit-hindiston", "Yarali kolitni Hindistonda davolash", "yarali kolit", "gastroenterologiya", "yarali kolit terapiyasi", "qonli diareya|tez hojatga chiqish|qorin og‘rig‘i", "kolonoskopiya va biopsiya|najas yallig‘lanish markeri|qon tahlillari", "5-ASA yoki steroid|immun va biologik terapiya|kolektomiya zarur bo‘lsa", "remissiya, ovqatlanish va yo‘g‘on ichak skriningi"],
  ["gepatit-davolash-hindiston", "Virusli gepatitni Hindistonda davolash", "virusli gepatit", "gepatologiya", "gepatit terapiyasi", "holsizlik|sariqlik|jigar fermentlari ko‘tarilishi", "virus yuklamasi va turi|jigar funksiyasi|fibroz bahosi va ultratovush", "virusga qarshi dorilar|jigarni asrash|asoratlarni boshqarish", "virus javobi, jigar salomatligi va saraton skriningi"],
  ["jigar-sirrozi-hindiston", "Jigar sirrozini Hindistonda davolash", "jigar sirrozi", "gepatologiya", "sirroz va asoratlarini davolash", "qorin shishi|sariqlik|qon ketishi yoki hushyorlik o‘zgarishi", "jigar va ivish tahlillari|ultratovush yoki elastografiya|endoskopiya va transplant bahosi", "sababga qaratilgan davo|assit va portal gipertenziya nazorati|transplantatsiya", "tuz nazorati, dorilar, infeksiya va saraton skriningi"],
  ["pankreatit-davolash-hindiston", "Pankreatitni Hindistonda davolash", "o‘tkir yoki surunkali pankreatit", "gastroenterologiya va pankreatobiliar jarrohlik", "pankreatit terapiyasi", "orqaga tarqaluvchi qorin og‘rig‘i|ko‘ngil aynishi|vazn kamayishi yoki yog‘li najas", "lipaza va qon tahlillari|KT yoki MRT/MRCP|endoskopik ultratovush", "suyuqlik va og‘riq nazorati|endoskopik drenaj|jarrohlik tanlangan holatda", "alkogol va chekishdan saqlanish, fermentlar va ovqatlanish"],
  ["ot-pufagi-operatsiyasi", "Hindistonda o‘t pufagi operatsiyasi", "o‘t pufagi toshi va yallig‘lanishi", "gepatobiliar jarrohlik", "laparoskopik xoletsistektomiya", "o‘ng qovurg‘a ostida og‘riq|yog‘li ovqatdan keyin bezovtalik|isitma yoki sariqlik", "ultratovush|jigar va yallig‘lanish tahlillari|MRCP zarur bo‘lsa", "simptom nazorati|laparoskopik xoletsistektomiya|o‘t yo‘li toshida ERCP", "kesma parvarishi va ovqatni bosqichma-bosqich tiklash"],
  ["churra-operatsiyasi-hindiston", "Hindistonda churra operatsiyasi", "qorin devori churrasi", "umumiy jarrohlik", "churrani laparoskopik yoki ochiq tuzatish", "zo‘riqishda paydo bo‘ladigan bo‘rtma|og‘riq|bo‘rtmaning qaytmasligi", "jarroh ko‘rigi|ultratovush yoki KT murakkab holatda|operatsiya oldi baholash", "ochiq plastika|laparoskopik plastika|robotik rekonstruksiya", "og‘irlik ko‘tarmaslik, yara parvarishi va bosqichli faollashish"],
  ["gemorroy-davolash-hindiston", "Gemorroy kasalligini Hindistonda davolash", "gemorroy", "koloproktologiya", "gemorroyni minimal invaziv davolash", "hojatdan keyin qon|qichishish yoki og‘riq|tugun chiqishi", "proktologik ko‘rik|anoskopiya|yosh va belgiga qarab kolonoskopiya", "tolali ovqat va dori|rezina halqa yoki lazer muolajasi|gemorroy operatsiyasi", "ich qotishini oldini olish, gigiyena va og‘riq nazorati"],
  ["revmatoid-artrit-hindiston", "Revmatoid artritni Hindistonda davolash", "revmatoid artrit", "revmatologiya", "kasallikni o‘zgartiruvchi revmatologik terapiya", "ertalabki bo‘g‘im qotishi|simmetrik shish va og‘riq|charchoq", "revmatolog ko‘rigi|RF va anti-CCP|yallig‘lanish tahlili va tasvir", "DMARD dorilar|biologik yoki maqsadli terapiya|fizioterapiya", "remissiya monitoringi, vaksina va bo‘g‘imni himoya qilish"],
  ["ankilozlovchi-spondilit", "Ankilozlovchi spondilitni Hindistonda davolash", "ankilozlovchi spondilit", "revmatologiya", "aksial spondiloartrit terapiyasi", "yoshda boshlangan bel og‘rig‘i|ertalab qotish|harakat bilan yengillashish", "sakroiliak MRT yoki rentgen|yallig‘lanish tahlillari|ko‘z va boshqa organlar bahosi", "mashq va NSAID|biologik terapiya|deformatsiyada jarrohlik", "kundalik cho‘zilish, gavda va yurak-o‘pka salomatligi"],
  ["lupus-davolash-hindiston", "Tizimli qizil yugurikni Hindistonda davolash", "tizimli qizil yugurik", "revmatologiya", "lupus terapiyasi", "bo‘g‘im og‘rig‘i|quyoshga sezgir toshma|buyrak yoki qon o‘zgarishlari", "ANA va maxsus antitanalar|siydik va buyrak tahlili|organ zarari bahosi", "gidroksixloroxin|steroid va immunosupressiya|biologik terapiya tanlangan holatda", "quyoshdan himoya, infeksiya profilaktikasi va organ monitoringi"],
  ["sport-jarohatlari-hindiston", "Sport jarohatlarini Hindistonda davolash", "sport jarohatlari", "sport ortopediyasi", "sport jarohatini tiklash", "harakatda og‘riq|shish yoki beqarorlik|sport natijasining pasayishi", "sport shifokori ko‘rigi|ultratovush yoki MRT|harakat biomexanikasi", "fizioterapiya|artroskopik ta’mirlash|kuch va koordinatsiya dasturi", "mezonlarga asoslangan sportga xavfsiz qaytish"],
  ["oldingi-xochsimon-boglam-acl", "ACL bog‘lamini Hindistonda tiklash", "oldingi xochsimon bog‘lam shikasti", "sport ortopediyasi", "ACL rekonstruksiyasi", "tizzaning bo‘shashib ketishi|jarohatdan keyin shish|burilish harakatida ishonchsizlik", "klinik barqarorlik testlari|MRT|oyoq kuchi va harakat bahosi", "reabilitatsiya|artroskopik ACL rekonstruksiyasi|meniskni bir vaqtda ta’mirlash", "shish nazorati, kuch, sakrash va sport sinovlari"],
  ["yelka-artroskopiyasi-hindiston", "Hindistonda yelka artroskopiyasi", "yelka payi va labrum shikastlari", "yelka ortopediyasi", "yelka artroskopiyasi", "qo‘lni ko‘tarishda og‘riq|kechasi og‘riq|yelka beqarorligi", "klinik ko‘rik|rentgen|MRT yoki MR-artrografiya", "fizioterapiya va ineksiya|artroskopik pay ta’miri|beqarorlikni tuzatish", "sling rejimi, bosqichli harakat va kuchni tiklash"],
  ["oyoq-qol-deformatsiyasi", "Oyoq-qo‘l deformatsiyasini Hindistonda tuzatish", "tug‘ma yoki orttirilgan oyoq-qo‘l deformatsiyasi", "rekonstruktiv ortopediya", "deformatsiyani korreksiya qilish", "oyoq uzunligi farqi|qiyshayish|yurish yoki kundalik faoliyat qiyinligi", "tik holatda rentgen|KT zarur bo‘lsa|yurish va bo‘g‘im bahosi", "osteotomiya|tashqi fiksator bilan bosqichli tuzatish|rekonstruktiv jarrohlik", "suyak bitishi, pin parvarishi va yurish reabilitatsiyasi"],
  ["miya-anevrizmasi-hindiston", "Miya anevrizmasini Hindistonda davolash", "miya anevrizmasi", "neyrovaskulyar jarrohlik", "anevrizmani kliplash yoki endovaskulyar yopish", "to‘satdan eng kuchli bosh og‘rig‘i|ko‘rish o‘zgarishi|tasodifan topilgan anevrizma", "KT/KT-angiografiya|MRT-angiografiya|raqamli angiografiya", "kuzatuv|endovaskulyar koiling yoki flow diverter|mikrojarrohlik kliplash", "qon bosimi, nevrologik belgilar va nazorat angiografiyasi"],
  ["miya-qon-tomir-malformatsiyasi", "Miya AVM kasalligini Hindistonda davolash", "arteriovenoz malformatsiya", "neyrovaskulyar neyroxirurgiya", "AVMni kompleks davolash", "tutqanoq|bosh og‘rig‘i|miya qon ketishi yoki nevrologik nuqson", "MRT|KT-angiografiya|raqamli angiografiya", "endovaskulyar embolizatsiya|mikrojarrohlik|stereotaktik radiojarrohlik", "tutqanoq va nevrologik holat, bosqichli tasviriy kuzatuv"],
  ["gidrosefaliya-davolash", "Gidrosefaliyani Hindistonda davolash", "gidrosefaliya", "neyroxirurgiya", "shunt yoki endoskopik davolash", "bosh og‘rig‘i va qusish|yurish hamda xotira o‘zgarishi|bolada bosh aylanasining kattalashishi", "miya MRT yoki KT|ko‘z tubi va nevrologik ko‘rik|bosim bahosi zarur bo‘lsa", "ventrikuloperitoneal shunt|endoskopik uchinchi ventrikulostomiya|sababni davolash", "shunt nosozligi va infeksiya belgilarini bilish"],
  ["trigeminal-nevralgiya", "Trigeminal nevralgiyani Hindistonda davolash", "trigeminal nevralgiya", "funksional neyroxirurgiya", "yuz og‘rig‘ini davolash", "yuzda elektr toki kabi og‘riq|tegish yoki chaynash bilan xuruj|bir tomonlama takroriy og‘riq", "nevrologik ko‘rik|maxsus miya MRT|tish va boshqa sabablarni istisno qilish", "dori|mikrovaskulyar dekompressiya|radiochastota yoki radiojarrohlik", "og‘riq kundaligi, dori va yuz sezgisini kuzatish"],
  ["sezaryen-keyingi-bepushtlik", "Ikkilamchi bepushtlikni Hindistonda davolash", "ikkilamchi bepushtlik", "reproduktologiya", "homiladorlikni qayta rejalashtirish", "oldingi homiladorlikdan keyin uzoq muddat homilador bo‘lmaslik|hayz o‘zgarishi|tos og‘rig‘i", "juftlik fertilitet bahosi|bachadon chandig‘i va naylar|tuxumdon zaxirasi va spermogramma", "ovulyatsiya yoki jarrohlik davosi|IUI|IVF yoki ICSI", "sog‘lom homiladorlikka tayyorgarlik va erta kuzatuv"],
  ["surrogat-onalik-hindiston-qonunlari", "Hindistonda surrogat onalik: qonuniy va tibbiy jihatlar", "surrogat onalikni ko‘rib chiqayotgan oilalar holati", "reproduktiv tibbiyot", "qonuniy mos fertilitet maslahatlari", "homilani ko‘tara olmaslik tashxisi|takroriy muvaffaqiyatsiz homiladorlik|qonuniy imkoniyatni aniqlash ehtiyoji", "reproduktiv mutaxassis bahosi|tibbiy hujjatlar|amaldagi qonun va huquqiy muvofiqlik tekshiruvi", "ruxsat etilgan fertilitet variantlari|IVF|boshqa davlat yoki mahalliy qonuniy yo‘llar bo‘yicha maslahat", "huquqiy hujjatlar va davomiy tibbiy kuzatuv"],
  ["donor-tuxum-hujayra-ivf", "Donor tuxum hujayrasi bilan IVF Hindistonda", "tuxumdon zaxirasi keskin kamaygan bepushtlik", "reproduktologiya", "donor oosit bilan IVF", "past AMH|takroriy IVF muvaffaqiyatsizligi|irsiy kasallik xavfi", "bachadon va umumiy salomatlik bahosi|spermogramma|amaldagi qonuniy mezonlarni tekshirish", "donor oosit IVF|embrion ko‘chirish|qo‘llab-quvvatlovchi gormonal davolash", "erta homiladorlik monitoringi va dori jadvali"],
  ["embriyon-genetik-tekshiruvi", "IVFda embrion genetik tekshiruvi (PGT) Hindistonda", "genetik xavf bilan bog‘liq reproduktiv holatlar", "reproduktiv genetika", "preimplantatsion genetik test", "irsiy kasallik oilaviy tarixi|takroriy homila yo‘qotish|takroriy IVF muvaffaqiyatsizligi", "genetik maslahat|ota-ona genetik tahlili|IVF va embrion biopsiyasi rejasini baholash", "PGT-M yoki PGT-SR ko‘rsatmaga ko‘ra|IVF/ICSI|tekshirilgan embrion ko‘chirish", "natijani genetik talqin qilish va prenatal test rejasini tuzish"],
  ["yuqori-xavfli-homiladorlik", "Hindistonda yuqori xavfli homiladorlikni boshqarish", "yuqori xavfli homiladorlik", "maternal-fetal tibbiyot", "perinatal kuzatuv va davolash", "yuqori qon bosimi yoki diabet|homila o‘sishi muammosi|oldingi murakkab homiladorlik", "ekspert ultratovush|ona qon va organ tahlillari|homila monitoringi va genetik skrining", "dori va yaqin kuzatuv|homila ichidagi muolaja ayrim holatda|rejalashtirilgan tug‘ruq", "ona va chaqaloq uchun tug‘ruqdan keyingi nazorat"],
  ["neonatal-jarrohlik-hindiston", "Hindistonda yangi tug‘ilgan chaqaloqlar jarrohligi", "tug‘ma jarrohlik kasalliklari", "neonatal va pediatrik jarrohlik", "yangi tug‘ilgan chaqaloq operatsiyasi", "ovqatlana olmaslik|qorin shishi yoki qusish|tug‘ma nuqsonning prenatal aniqlanishi", "neonatolog ko‘rigi|ultratovush, rentgen yoki MRT|yurak va anesteziya bahosi", "minimal invaziv yoki ochiq jarrohlik|intensiv neonatal yordam|bosqichli rekonstruksiya", "ovqatlantirish, yara, o‘sish va rivojlanish nazorati"],
  ["autizm-reabilitatsiyasi-hindiston", "Hindistonda autizm uchun rivojlantiruvchi reabilitatsiya", "autizm spektridagi rivojlanish ehtiyojlari", "rivojlanish pediatriyasi", "individual rivojlantiruvchi terapiya", "nutq va muloqot kechikishi|takroriy xatti-harakat|sensor sezgirlik", "rivojlanish pediatri bahosi|nutq va ergoterapiya bahosi|eshitish va qo‘shimcha holatlar skriningi", "ota-ona ishtirokidagi rivojlantiruvchi terapiya|nutq terapiyasi|ergoterapiya va ta’lim yordami", "oilaviy maqsadlar, kundalik ko‘nikmalar va maktab bilan hamkorlik"],
  ["serebral-falaj-reabilitatsiyasi", "Hindistonda serebral falaj reabilitatsiyasi", "serebral falaj", "pediatrik reabilitatsiya", "ko‘p tarmoqli bolalar reabilitatsiyasi", "harakat rivojining kechikishi|mushak tarangligi|yurish, ovqatlanish yoki nutq qiyinligi", "rivojlanish va harakat bahosi|son va umurtqa tasviri zarur bo‘lsa|yutish hamda nutq bahosi", "fizioterapiya va ergoterapiya|spastiklikni boshqarish|ortopedik yoki neyroxirurgik muolaja tanlangan holatda", "funksional maqsadlar, yordamchi moslama va oilaviy mashqlar"],
  ["kosmetik-jarrohlik-hindiston", "Hindistonda plastik va kosmetik jarrohlik", "estetik yoki rekonstruktiv ehtiyojlar", "plastik jarrohlik", "individual plastik jarrohlik", "tashqi ko‘rinishdan funksional yoki estetik bezovtalik|jarohat yoki operatsiyadan keyingi nuqson|realistik natija bo‘yicha maslahat ehtiyoji", "plastik jarroh konsultatsiyasi|salomatlik va yara bitishi xavfi|standartlashtirilgan surat va reja", "rekonstruktiv jarrohlik|tana yoki yuz estetik operatsiyasi|nojarrohlik muolajalar", "shish, chandiq, kompression kiyim va realistik tiklanish"],
  ["yuz-jag-jarrohligi-hindiston", "Hindistonda yuz-jag‘ jarrohligi", "yuz, jag‘ va og‘iz kasalliklari", "maksillofatsial jarrohlik", "yuz-jag‘ rekonstruktiv operatsiyasi", "jag‘ yopilishining buzilishi|yuz assimetriyasi|jarohat yoki o‘sma nuqsoni", "3D KT|tish va okklyuziya bahosi|virtual jarrohlik rejalash", "ortognatik jarrohlik|travma rekonstruksiyasi|o‘sma rezeksiya va rekonstruksiya", "og‘iz gigiyenasi, yumshoq ovqat va jag‘ funksiyasi"],
  ["kuyish-rekonstruksiyasi-hindiston", "Hindistonda kuyishdan keyingi rekonstruksiya", "kuyish chandiqlari va kontrakturalar", "rekonstruktiv plastik jarrohlik", "kuyish rekonstruksiyasi", "bo‘g‘im harakatining chandiq bilan cheklanishi|og‘riqli yoki beqaror chandiq|yuz va tana deformatsiyasi", "chandiq va harakat bahosi|qon ta’minoti va tasvir zarur bo‘lsa|reabilitatsiya ehtiyoji", "chandiq bo‘shatish va teri ko‘chirish|to‘qima kengaytirish|mikrojarrohlik rekonstruksiya", "splint, kompressiya, chandiq parvarishi va fizioterapiya"],
  ["qol-jarrohligi-hindiston", "Hindistonda qo‘l jarrohligi", "qo‘l nervi, payi va bo‘g‘im kasalliklari", "qo‘l va mikrojarrohlik", "qo‘l funksiyasini tiklash operatsiyasi", "ushlash kuchining pasayishi|uvishish|pay yoki barmoq harakati cheklanishi", "qo‘l jarrohi ko‘rigi|rentgen yoki MRT|nerv o‘tkazuvchanligi testi", "nerv dekompressiyasi|pay yoki bog‘lam ta’miri|mikrojarrohlik rekonstruksiya", "shina, shish nazorati va maxsus qo‘l terapiyasi"],
  ["ikkinchi-tibbiy-fikr-hindiston", "Hindistondan ikkinchi tibbiy fikr olish", "murakkab yoki noaniq tashxis", "multidisiplinar tibbiy maslahat", "ekspert ikkinchi tibbiy fikri", "tashxisga shubha|katta operatsiya tavsiyasi|bir nechta davolash yo‘li orasida tanlov", "hujjatlarni tartiblash|tasvir va patologiyani qayta ko‘rish|tegishli ekspert konsultatsiyasi", "mavjud rejani tasdiqlash|qo‘shimcha tekshiruv|muqobil davolash variantini muhokama qilish", "mahalliy shifokor bilan kelishilgan amaliy keyingi qadamlar"],
  ["onlayn-shifokor-konsultatsiyasi", "Hindiston shifokori bilan onlayn konsultatsiya", "masofadan ekspert bahosi talab qiladigan tibbiy holat", "telemeditsina", "video konsultatsiya", "xorijga borishdan oldin fikr olish ehtiyoji|tibbiy hujjatlar bo‘yicha savol|davolash rejasini tushunish istagi", "raqamlashtirilgan tibbiy hujjatlar|tasvir fayllari|oldindan tuzilgan savollar", "video maslahat|yozma ekspert xulosasi mavjud bo‘lsa|yuzma-yuz ko‘rik tavsiyasi zarur bo‘lsa", "tavsiyalarni mahalliy shifokor bilan muvofiqlashtirish"],
  ["hindiston-shifoxonasini-tanlash", "Hindistonda shifoxona tanlash: xavfsiz mezonlar", "davolash uchun shifoxona tanlash ehtiyoji", "tibbiy turizm koordinatsiyasi", "shifoxona va mutaxassisni moslashtirish", "bir nechta taklif orasida noaniqlik|murakkab kasallik uchun markaz izlash|xarajat va sifatni solishtirish ehtiyoji", "kasallik va bosqichni aniqlash|markaz tajribasi va akkreditatsiya ma’lumoti|yozma davolash taklifi", "birlamchi markaz tanlovi|ikkinchi ekspert fikri|multidisiplinar markazga yo‘naltirish", "aniq aloqa, hujjatlar va keyingi kuzatuv mas’uliyatini belgilash"],
  ["hindistondagi-eng-yaxshi-onkologlar", "Hindistonda onkolog tanlash bo‘yicha amaliy qo‘llanma", "onkolog mutaxassis tanlash ehtiyoji", "onkologiya", "onkolog va markazni moslashtirish", "saraton tashxisi|davolash rejasi bo‘yicha ikkinchi fikr|muayyan o‘sma turiga ekspert izlash", "patologiya va bosqichni tasdiqlash|mutaxassisning o‘sma turi bo‘yicha tajribasi|tumor board imkoniyati", "jarrohlik onkologi|tibbiy onkolog|radiatsion onkolog konsiliumi", "mahalliy nazorat va xorijiy markaz bilan aloqa rejasini tuzish"],
  ["hindistondagi-kardiojarrohlar", "Hindistonda kardiojarroh tanlash bo‘yicha qo‘llanma", "yurak operatsiyasi uchun ekspert tanlash ehtiyoji", "kardiojarrohlik", "kardiojarroh va markazni moslashtirish", "operatsiya tavsiyasi|murakkab klapan yoki koronar kasallik|ikkinchi fikr ehtiyoji", "angiografiya va EхоKGni ko‘rib chiqish|jarroh tajribasi|markaz intensiv yordam imkoniyati", "ochiq yurak operatsiyasi|minimal invaziv usul|kateter va jarrohlik konsiliumi", "operatsiyadan keyingi kardio-reabilitatsiya va masofaviy nazorat"],
  ["hindistonda-davolanish-narxlari", "Hindistonda davolanish narxlari: smetani tushunish", "xalqaro davolanish xarajatlarini rejalashtirish", "tibbiy turizm", "individual yozma davolash smetasi", "narxlar orasidagi katta farq|qaysi xizmatlar kirishini bilmaslik|qo‘shimcha xarajat xavfi", "tibbiy hujjatlar asosida reja|shifoxona yozma smetasi|safar va tiklanish ehtiyojlari", "bazaviy davolash paketi|murakkablikka qarab kengaytirilgan davo|mahalliy kuzatuv bilan kombinatsiya", "moliyaviy zaxira va tibbiy kuzatuvni oldindan rejalash"],
  ["saraton-davolash-narxi-hindiston", "Hindistonda saraton davolash narxi nimaga bog‘liq?", "onkologik davolanish xarajatlarini rejalashtirish", "onkologiya", "individual onkologik smeta", "bosqich va reja noaniqligi|bir nechta terapiya turi|davolash davomiyligini hisoblash ehtiyoji", "patologiya va bosqich|dori va radiatsiya rejasi|jarrohlik hamda yotish zarurati", "jarrohlik paketi|dori sikllari|radioterapiya kursi", "kutilmagan tibbiy ehtiyojlar uchun zaxira va kuzatuv budjeti"],
  ["yurak-operatsiyasi-narxi-hindiston", "Hindistonda yurak operatsiyasi narxi va smeta tarkibi", "yurak operatsiyasi xarajatlarini rejalashtirish", "kardiojarrohlik", "individual yurak operatsiyasi smetasi", "operatsiya turi noaniqligi|implant narxi haqida savol|reanimatsiya va yotish xarajatini bilish ehtiyoji", "angiografiya va EхоKG|operatsiya turi|implant, reanimatsiya va xavf bahosi", "angioplastika|koronar shuntlash|klapan muolajasi", "dori, kardio-reabilitatsiya va nazorat xarajatlarini rejalash"],
  ["transplantatsiya-narxi-hindiston", "Hindistonda transplantatsiya narxi va qonuniy jarayon", "organ transplantatsiyasi xarajatlarini rejalashtirish", "transplantologiya", "qonuniy transplantatsiya dasturi va smeta", "donor tekshiruvlari haqida savol|uzoq yotish ehtiyoji|operatsiyadan keyingi dori xarajati", "donor va retsipiyent bahosi|qonuniy hujjatlar|operatsiya va reanimatsiya rejasi", "transplantatsiya oldi tayyorgarlik|operatsiya|immunosupressiya va kuzatuv", "uzoq muddatli dori va laborator nazorat budjeti"],
  ["tibbiy-viza-hindiston", "Hindiston tibbiy vizasi: O‘zbekistonliklar uchun qo‘llanma", "Hindistonga davolanish safari", "tibbiy turizm koordinatsiyasi", "tibbiy viza uchun tayyorgarlik", "davolash sanasi yaqinligi|taklif xati zarurati|hamroh viza hujjatlari bo‘yicha savol", "pasport va ariza ma’lumotlari|Hindiston shifoxonasi taklif xati|amaldagi rasmiy viza talablarini tekshirish", "tibbiy viza arizasi|tibbiy hamroh vizasi|zarur bo‘lsa rasmiy idoradan aniqlik olish", "viza shartlari va ro‘yxatdan o‘tish talablariga rioya qilish"],
  ["hindistonga-tibbiy-safar", "Hindistonga tibbiy safar: bosqichma-bosqich reja", "davolanish uchun xalqaro safar", "xalqaro bemorlar koordinatsiyasi", "tibbiy safarni tashkil etish", "hujjatlar ko‘pligi|safar va davolash sanasini moslash|hamroh va yashashni rejalash ehtiyoji", "tibbiy xulosa va taklif|pasport-viza hujjatlari|parvozga yaroqlilik va dori ro‘yxati", "masofaviy fikr|rejalashtirilgan safar|zarur murakkab holatda tibbiy transport", "uyga qaytish xulosasi, dori zaxirasi va mahalliy nazorat"],
  ["hindistonda-tarjimon-xizmati", "Hindistonda tibbiy tarjimon xizmati", "davolanish paytida til yordami ehtiyoji", "xalqaro bemorlar yordami", "tibbiy tarjimonlik koordinatsiyasi", "tashxisni to‘liq tushunmaslik|rozilik hujjatlarida til to‘sig‘i|shifokorga aniq savol bera olmaslik", "kerakli til va tibbiy yo‘nalish|uchrashuvlar jadvali|hujjat tarjimasi hajmi", "og‘zaki tarjima|yozma tibbiy tarjima|masofaviy tarjimon yordami", "chiqarish xulosasi va dori ko‘rsatmalarini tushunarli olish"],
  ["hindistonda-yashash-va-transport", "Hindistonda davolanish paytida yashash va transport", "davolanish davridagi logistika", "xalqaro bemorlar yordami", "yashash va mahalliy transportni rejalash", "uzoq ambulator davolash|harakat cheklanishi|shifoxonaga yaqin turar joy ehtiyoji", "davolash jadvali|bemorning harakat va gigiyena ehtiyoji|hamrohlar soni va budjet", "mehmonxona|servis apartament|moslashtirilgan transport", "chiqarilgandan keyin xavfsiz turar joy va aeroport transferi"],
  ["davolanishdan-keyin-kuzatuv", "Hindistonda davolanishdan keyingi kuzatuv", "xorijda davolanishdan keyingi nazorat ehtiyoji", "xalqaro bemorlar koordinatsiyasi", "masofaviy va mahalliy follow-up", "dori rejasi bo‘yicha savol|yangi simptom|nazorat tekshiruv sanasini aniqlash ehtiyoji", "chiqarish xulosasi|operatsiya va patologiya hujjatlari|mahalliy shifokor ma’lumoti", "rejalashtirilgan video nazorat|mahalliy laborator va tasviriy tekshiruv|zarur bo‘lsa qayta safar", "uzluksiz tibbiy aloqa va favqulodda belgilar rejasiga rioya"],
  ["tibbiy-hujjatlarni-tarjima-qilish", "Tibbiy hujjatlarni Hindiston shifoxonasi uchun tayyorlash", "xalqaro ekspert ko‘rigiga hujjat tayyorlash", "tibbiy koordinatsiya", "tibbiy hujjatlarni saralash va tarjima qilish", "hisobotlar turli joyda saqlanishi|tashxis xulosasi yo‘qligi|tasvir fayllarini yuborish qiyinligi", "xronologik tibbiy xulosa|laborator va patologiya hisobotlari|DICOM tasvirlari", "professional tarjima|qisqa klinik xulosa|xavfsiz elektron yuborish", "yangilangan hujjat to‘plami va maxfiylikni saqlash"],
  ["hindistonda-reabilitatsiya", "Hindistonda kompleks reabilitatsiya", "operatsiya, jarohat yoki kasallikdan keyingi funksional cheklanish", "jismoniy va reabilitatsion tibbiyot", "individual reabilitatsiya dasturi", "yurish yoki kundalik ish qiyinligi|og‘riq va kuchsizlanish|nutq yoki yutish muammosi", "reabilitolog bahosi|harakat va kundalik faoliyat testlari|nutq, yutish yoki kognitiv baho", "fizioterapiya|ergoterapiya|nutq va psixologik reabilitatsiya", "o‘lchanadigan maqsadlar va uy mashqlari dasturi"],
  ["onkologik-reabilitatsiya", "Hindistonda onkologik reabilitatsiya", "saraton va uning davosi oqibatlari", "onkologik reabilitatsiya", "saraton davrida va undan keyin tiklanish", "kuchli charchoq|mushak kuchsizligi|limfedema yoki kundalik faoliyat cheklanishi", "reabilitolog va onkolog bahosi|ovqatlanish va funksional test|limfedema skriningi", "xavfsiz jismoniy mashq|limfedema terapiyasi|ovqatlanish va psixologik yordam", "energiya boshqaruvi, mustaqillik va saraton kuzatuvi bilan uyg‘unlik"],
  ["kardio-reabilitatsiya-hindiston", "Hindistonda yurak reabilitatsiyasi", "yurak xuruji yoki operatsiyadan keyingi holat", "kardio-reabilitatsiya", "nazoratli yurak tiklanish dasturi", "tez charchash|harakatdan qo‘rqish|qon bosimi yoki yurak xavf omillari", "kardiolog bahosi|EKG va harakat testi|ovqatlanish va xavf profili", "nazoratli mashq|yurak uchun ovqatlanish|stress va dori boshqaruvi", "mustaqil xavfsiz mashq va uzoq muddatli xavf kamaytirish"],
  ["ortopedik-reabilitatsiya", "Hindistonda ortopedik reabilitatsiya", "bo‘g‘im yoki suyak operatsiyasidan keyingi cheklanish", "ortopedik reabilitatsiya", "harakat va kuchni tiklash dasturi", "bo‘g‘im qotishi|mushak kuchsizligi|yurish qiyinligi", "harakat hajmi va kuch|yurish tahlili|og‘riq va yara holati", "fizioterapiya|gidroterapiya mavjud bo‘lsa|yordamchi moslama va uy mashqi", "xavfsiz yurish, muvozanat va kundalik faoliyat"],
  ["nevrologik-reabilitatsiya", "Hindistonda nevrologik reabilitatsiya", "insult, miya yoki orqa miya shikastidan keyingi holat", "nevrologik reabilitatsiya", "intensiv nevrologik tiklanish", "falaj yoki kuchsizlanish|muvozanat buzilishi|nutq, yutish yoki xotira qiyinligi", "nevrolog va reabilitolog bahosi|funksional va kognitiv test|yutish va nutq bahosi", "fizioterapiya va robotik mashqlar mavjud bo‘lsa|ergoterapiya|nutq va kognitiv terapiya", "mustaqillik, xavfsizlik va oila uchun uy dasturi"],
  ["orqa-miya-shikasti-reabilitatsiyasi", "Orqa miya shikastidan keyingi reabilitatsiya Hindistonda", "orqa miya shikasti", "spinal reabilitatsiya", "orqa miya jarohati reabilitatsiyasi", "qo‘l-oyoq falaji|sezgi yo‘qolishi|siydik pufagi va ichak nazorati muammosi", "shikast darajasi va funksional baho|teri va nafas holati|urologik baholash", "fizioterapiya va ergoterapiya|siydik-ichak dasturi|yordamchi texnologiya", "teri himoyasi, mustaqil transfer va jamiyatga qaytish"],
  ["amputatsiyadan-keyingi-protez", "Hindistonda amputatsiyadan keyingi protez va reabilitatsiya", "amputatsiyadan keyingi holat", "protezlash va reabilitatsiya", "individual protez moslash", "yurish yoki ushlash funksiyasi yo‘qolishi|qoldiq a’zo og‘rig‘i|protezga tayyorgarlik ehtiyoji", "qoldiq a’zo va yara bahosi|kuch va muvozanat|faoliyat maqsadlari", "qoldiq a’zoni tayyorlash|modul protez|yurish va kundalik ko‘nikma mashqi", "teri nazorati, protez parvarishi va bosqichli foydalanish"],
  ["tibbiy-evakuatsiya-hindiston", "Hindistonga tibbiy evakuatsiya va havo ambulansi", "parvozda tibbiy yordam talab qiladigan holat", "tibbiy transport koordinatsiyasi", "havo ambulansi yoki tibbiy eskort", "oddiy reysda xavfsiz ucha olmaslik|kislorod yoki monitoring ehtiyoji|tezkor markazlararo ko‘chirish", "parvozga yaroqlilik|bemor holati va uskunalar|qabul qiluvchi shifoxona tasdig‘i", "tibbiy eskortli reys|stretcher yoki kislorodli tijoriy reys|maxsus havo ambulansi", "qabul qiluvchi jamoaga uzluksiz topshirish va xavfsiz transport"],
  ["shoshilinch-davolanish-hindiston", "Hindistonda shoshilinch davolanishni muvofiqlashtirish", "vaqtga sezgir, lekin safarga yaroqliligi baholanadigan tibbiy holat", "xalqaro bemorlar koordinatsiyasi", "tezlashtirilgan shifoxona qabul jarayoni", "tez yomonlashayotgan holat|mahalliy imkoniyat cheklanishi|tez ekspert markazi zarurati", "mahalliy shoshilinch barqarorlashtirish|parvozga yaroqlilik|qabul qiluvchi shifokor va yotoq tasdig‘i", "mahalliy zudlik yordami|tibbiy transport|tezlashtirilgan xalqaro qabul", "bemor xavfsizligi va jamoalar o‘rtasida to‘liq klinik topshirish"],
  ["hindistonda-sogliq-tekshiruvi", "Hindistonda kompleks sog‘liq tekshiruvi", "profilaktik sog‘liq bahosi", "profilaktik tibbiyot", "individual check-up dasturi", "xavf omillari mavjudligi|yoshga mos skrining ehtiyoji|surunkali kasallik nazorati", "shaxsiy va oilaviy tarix|qon bosimi va laborator tahlillar|yosh-jinsga mos saraton skriningi", "profilaktik maslahat|xavf omillarini boshqarish|aniqlangan muammo bo‘yicha mutaxassis ko‘rigi", "natijalarni mahalliy shifokor bilan muhokama va yillik reja"],
  ["saraton-skriningi-hindiston", "Hindistonda saraton skriningi", "saraton xavfini erta baholash", "profilaktik onkologiya", "dalillarga asoslangan saraton skriningi", "yosh yoki oilaviy xavf|oldingi saratonoldi holati|skrining muddatini aniqlash ehtiyoji", "xavf anketasi|yosh va jinsga mos test|genetik maslahat ko‘rsatmaga ko‘ra", "mammografiya|bachadon bo‘yni skriningi|kolorektal yoki o‘pka skriningi mezonga ko‘ra", "natijani talqin qilish va keyingi tekshiruv muddatini belgilash"],
  ["genetik-test-hindiston", "Hindistonda tibbiy genetik test va maslahat", "irsiy kasallik xavfi", "tibbiy genetika", "genetik maslahat va maqsadli test", "oilada takroriy kasallik|yosh yoshda saraton|tug‘ma yoki rivojlanish holati", "uch avlodlik oilaviy tarix|genetik maslahat|klinik savolga mos test tanlash", "maqsadli gen testi|panel yoki ekzom ko‘rsatmaga ko‘ra|oila a’zolarini kaskad tekshirish", "natijaning tibbiy va oilaviy ma’nosini mutaxassis bilan talqin qilish"],
  ["kam-uchraydigan-kasalliklar", "Kam uchraydigan kasalliklarni Hindistonda tekshirtirish", "kam uchraydigan yoki tashxisi aniqlanmagan kasallik", "multidisiplinar diagnostika", "murakkab tashxis dasturi", "ko‘p mutaxassisga qaramay tashxis yo‘qligi|bir nechta organ tizimi belgisi|irsiy kasallik shubhası", "to‘liq klinik xronologiya|patologiya va tasvirni qayta ko‘rish|genetik yoki metabolik test", "simptomatik yordam|aniq tashxisga qaratilgan terapiya|klinik tadqiqot imkonini tekshirish", "bitta muvofiqlashtirilgan reja va mahalliy uzoq kuzatuv"],
  ["hindistonda-klinik-tadqiqotlar", "Hindistonda klinik tadqiqotlar: bemor uchun savollar", "standart davolashdan tashqari tadqiqot variantini ko‘rib chiqish", "klinik tadqiqotlar", "mos tadqiqotga qonuniy va etik yo‘naltirish", "standart davolash imkoniyatlari cheklanishi|yangi terapiya haqida qiziqish|tadqiqot mezonlarini bilish ehtiyoji", "aniq tashxis va bosqich|oldingi davolashlar|rasmiy ro‘yxat va qabul mezonlari", "standart terapiya|klinik tadqiqot|qo‘llab-quvvatlovchi yordam", "xabardor rozilik, nojo‘ya ta’sirlar va safar majburiyatlarini tushunish"],
  ["tibbiy-turizm-ozbekiston-hindiston", "O‘zbekiston–Hindiston tibbiy turizmi: xavfsiz bemor yo‘li", "O‘zbekistondan Hindistonga davolanish safari", "tibbiy turizm", "to‘liq davolanish koordinatsiyasi", "murakkab davolash izlash|xalqaro shifoxona bilan aloqa ehtiyoji|safar jarayonini tushunmaslik", "tibbiy hujjatlar|shifoxona va shifokor bahosi|yozma reja va smeta", "ikkinchi fikr|rejalashtirilgan davolash|reabilitatsiya va kuzatuv", "O‘zbekistondagi shifokor bilan uzluksiz nazorat va xavfsiz qaytish"],
  ["toshkentdan-hindistonga-davolanish", "Toshkentdan Hindistonga davolanish: amaliy qo‘llanma", "Toshkentdan xalqaro davolanish safari", "xalqaro bemorlar koordinatsiyasi", "Toshkentdan davolanish safarini tashkil etish", "hujjat va tarjima ehtiyoji|parvoz hamda qabul sanasini moslash|ishonchli aloqa nuqtasi izlash", "Toshkentdagi tibbiy hujjatlar|Hindiston shifoxonasi fikri|viza va safar tayyorgarligi", "masofaviy konsultatsiya|rejalashtirilgan qabul|operatsiya yoki terapiya dasturi", "chiqarish hujjatlari bilan Toshkentda kuzatuvni davom ettirish"],
  ["samarqanddan-hindistonga-davolanish", "Samarqanddan Hindistonga davolanish: bemorlar uchun yo‘l xaritasi", "Samarqanddan xalqaro davolanish safari", "xalqaro bemorlar koordinatsiyasi", "Samarqanddan davolanish safarini tashkil etish", "murakkab tashxis|Hindiston ekspertiga hujjat yuborish ehtiyoji|Toshkent orqali parvozni rejalash", "mahalliy tibbiy hujjatlar|masofaviy shifoxona bahosi|transport va viza rejasi", "ikkinchi fikr|rejalashtirilgan davolash|xorijdan keyingi mahalliy kuzatuv", "Samarqanddagi shifokor bilan natijalar va dori rejasini muvofiqlashtirish"],
  ["buxorodan-hindistonga-davolanish", "Buxorodan Hindistonga davolanish: to‘liq reja", "Buxorodan xalqaro davolanish safari", "xalqaro bemorlar koordinatsiyasi", "Buxorodan davolanish safarini tashkil etish", "xalqaro markazga yo‘llanma ehtiyoji|hujjat tarjimasi|yo‘l va hamrohni rejalash", "tibbiy xulosa va tasvirlar|Hindiston mutaxassisi bahosi|safarga yaroqlilik va logistika", "onlayn maslahat|rejalashtirilgan muolaja|uyga qaytgach kuzatuv", "Buxoroda laborator va klinik nazoratni oldindan kelishish"],
  ["fargonadan-hindistonga-davolanish", "Farg‘onadan Hindistonga davolanish: bosqichma-bosqich", "Farg‘onadan xalqaro davolanish safari", "xalqaro bemorlar koordinatsiyasi", "Farg‘onadan davolanish safarini tashkil etish", "ekspert davolash izlash|hujjatlarni xalqaro markazga yuborish|parvoz va yashashni rejalash", "tashxis hujjatlari|shifoxona yozma taklifi|viza va transport rejasi", "masofaviy ikkinchi fikr|Hindistonda davolash|mahalliy reabilitatsiya", "Farg‘onada kuzatuv va Hindiston jamoasi bilan aloqa"],
  ["namangandan-hindistonga-davolanish", "Namangandan Hindistonga davolanish: amaliy yo‘l xaritasi", "Namangandan xalqaro davolanish safari", "xalqaro bemorlar koordinatsiyasi", "Namangandan davolanish safarini tashkil etish", "murakkab davolash ehtiyoji|xalqaro shifoxona tanlash|hujjat, viza va logistika savollari", "tibbiy ma’lumotlarni saralash|ekspert fikri va smeta|safar xavfsizligi va viza", "onlayn konsultatsiya|rejalashtirilgan davolash|uyga qaytgach follow-up", "Namangandagi davolovchi shifokorga to‘liq chiqarish xulosasini yetkazish"],
  ["andijondan-hindistonga-davolanish", "Andijondan Hindistonga davolanish: bemor qo‘llanmasi", "Andijondan xalqaro davolanish safari", "xalqaro bemorlar koordinatsiyasi", "Andijondan davolanish safarini tashkil etish", "ixtisoslashgan markaz ehtiyoji|narx va davolash rejasini solishtirish|safar tafsilotlari", "tibbiy xulosa va DICOM|shifokor hamda markaz bahosi|viza, parvoz va yashash rejasi", "ikkinchi tibbiy fikr|Hindistonda muolaja|O‘zbekistonda tiklanish", "Andijonda uzluksiz nazorat va masofaviy qayta konsultatsiya"],
];

const toList = (value: string) => value.split("|");

const createFaqs = (
  title: string,
  condition: string,
  procedure: string,
  recoveryFocus: string,
): UzSeoFaq[] => [
  {
    question: `${procedure} uchun Hindistonga qachon borish kerak?`,
    answer: `${condition} bo‘yicha safar muddati masofaviy tibbiy ko‘rib chiqishdan keyin belgilanadi. Shifoxona tashxis, holatning shoshilinchligi, qo‘shimcha tekshiruvlar va bemorning parvozga yaroqliligini hisobga oladi. Favqulodda alomatlarda xorijga safarni kutmasdan mahalliy shoshilinch yordamga murojaat qilish kerak.`,
  },
  {
    question: "Dastlab qaysi tibbiy hujjatlar kerak bo‘ladi?",
    answer: "Odatda qisqa tibbiy xulosa, so‘nggi konsultatsiyalar, laborator natijalar, operatsiya bayonnomalari, patologiya javoblari va DICOM formatidagi tasvirlar kerak bo‘ladi. Aniq ro‘yxat kasallik va shifoxona talabiga qarab o‘zgaradi.",
  },
  {
    question: "Davolash narxi oldindan ma’lum bo‘ladimi?",
    answer: "Tibbiy hujjatlar ko‘rib chiqilgach, shifoxona taxminiy yozma reja va smeta berishi mumkin. Yakuniy xarajat qo‘shimcha tashxis, kasallik murakkabligi, implant yoki dori tanlovi, yotish muddati va asoratlar sabab o‘zgarishi mumkin.",
  },
  {
    question: "Hindistonda qancha vaqt qolish kerak?",
    answer: `Muddat tekshiruv, ${procedure.toLowerCase()} va shifokor ruxsat bergan xavfsiz tiklanish davriga bog‘liq. Qaytishdan oldin ${recoveryFocus} bo‘yicha aniq yozma ko‘rsatma olish muhim.`,
  },
  {
    question: "MedPobeda Group tashxis yoki davolashni belgilaydimi?",
    answer: "Yo‘q. MedPobeda Group tibbiy xizmat ko‘rsatuvchi emas; u hujjatlar, shifoxona aloqasi va safar jarayonini muvofiqlashtiradi. Tashxis, muolaja, prognoz va tibbiy qarorlar faqat litsenziyalangan shifokorlar tomonidan beriladi.",
  },
  {
    question: `${title} bo‘yicha ikkinchi fikr olish mumkinmi?`,
    answer: "Ha. Hujjatlar yetarli bo‘lsa, tegishli mutaxassis masofadan dastlabki fikr berishi mumkin. Ayrim qarorlar esa fizik ko‘rik, yangi tasvirlar, biopsiya yoki laborator tekshiruvdan keyingina tasdiqlanadi.",
  },
];

// The requested publishing batch is intentionally capped at exactly 100 URLs.
const publishingSeeds = seeds.slice(0, 100);

export const uzMedicalSeoPages: UzMedicalSeoPage[] = publishingSeeds.map(
  ([slug, title, condition, specialty, procedure, symptoms, diagnostics, treatments, recoveryFocus]) => {
    const shortTitle = title.split(":")[0];
    return {
      slug,
      title,
      shortTitle,
      condition,
      specialty,
      procedure,
      audience: "O‘zbekistondan Hindistonda davolanishni ko‘rib chiqayotgan bemorlar va ularning yaqinlari",
      symptoms: toList(symptoms),
      diagnostics: toList(diagnostics),
      treatments: toList(treatments),
      recoveryFocus,
      image: {
        src: "/images/hero/medical-tourism-overview.jpg",
        filename: `${slug}.jpg`,
        alt: `${shortTitle} bo‘yicha Hindistondagi shifoxonada shifokor va bemor konsultatsiyasi`,
        caption: `${shortTitle}: tekshiruv, davolash va tiklanishni oldindan rejalashtirish muhim.`,
        title: `${shortTitle} — MedPobeda Group`,
      },
      faqs: createFaqs(shortTitle, condition, procedure, recoveryFocus),
    };
  },
);

export const uzMedicalSeoPageBySlug = new Map(
  uzMedicalSeoPages.map((page) => [page.slug, page]),
);
